[[message]]
key = 'CUSTOM_SKILL_INFO_01_8'
old = '''
前方に猛ダッシュしつつ鋭い突き攻撃を放つ
突進距離に応じて威力が上昇する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で最大移動距離が延長／
突進距離最長時に敵のガード状態を崩す</COL>'''
new = '''
Rushes at the target and visits a powerful blow
upon them. Damage increases the further you dash.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases maximum rush distance.
Breaks enemy guard when rushing at maximum range.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_12'
old = '''
足元から直上へ鋭く斬り上げ、
軽量の敵を上空へ打ち上げる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で速度上昇／攻撃ヒット数増加</COL>'''
new = '''
Traces a grand skyward arc with the blade,
sending lightweight foes into the air.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases attack speed and number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_10'
old = '''
盾による打撃特化の連続攻撃を繰り出す。敵を怯ませ
やすく、ボタンの連打で攻撃回数が増加する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６でモーション変化／
最大攻撃回数増加（３→５）</COL>'''
new = '''
Unleashes a barrage of strikes using the shield.
Easily staggers enemy. Can be used continously.
<COL ffdc78>LV UP: Increases damage.
LV.6: Motion changes.
Increases number of hits (3→5).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_13'
old = '''
頭上に連続斬りを繰り出す
ボタンの連打で攻撃回数が増加する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で速度上昇／
最大攻撃回数増加（３→５）</COL>'''
new = '''
Looses a flurry of skyward slashes well-suited
to bringing flying foes to the ground.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases attack speed.
Increases maximum number of continous strikes (3→5).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_15'
old = '''
後方に身を逸らし、すぐさま間合いを詰めて斬り払う
敵の攻撃を回避しつつ繰り出せば威力が上昇する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で受付時間延長／
回避成功時、攻撃ヒット数増加</COL>'''
new = '''
Ducks backward afore charging in to deliver a slashing blow.
Using it as an evasive maneuver increases its power.
<COL ffdc78>LV UP: Increases damage.
LV.6: Extends evasion time.
When an attack is evaded, increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_9'
old = '''
跳躍し、鋭い一撃を放って下方に突き立てる
落下距離により威力が上昇
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加</COL> '''
new = '''
Leap forward and stab your sword into the ground.
<COL ff7878>Effective against War-Ready enemies.</COL>
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_11'
old = '''
盾で前方ガードを固めつつ、連続突きを繰り出す
ボタンの連打で攻撃回数が増加する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で速度上昇／最大攻撃回数増加（５→８）</COL>'''
new = '''
Unleashes a flurry of stabbing attacks while
maintaining the user's guard. Can be used continously.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases attack speed.
Increases maximum number of strikes (5→8).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_14'
old = '''
円弧状に剣先を一回転させ、周囲の敵をなぎ払う
のけぞり中にも発動可能
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６でモーション変化／攻撃ヒット数増加</COL>'''
new = '''
Spins with blade extended, drawing a deadly
circle especially effective when surrounded.
Employable while under attack.
<COL ffdc78>LV UP: Increases damage.
LV.6: Motion changes. Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_18'
old = '''
盾を構えながら素早く踏み込む
<PADM>左スティック<KEYM>移動キー</KEYM>により特定方向に移動できる
<COL ffdc78>LV UP毎に防御性能の上昇／スタミナ消費減少
LV.６で移動速度上昇／移動方向に左右追加</COL>'''
new = '''
A quick forward lunge while guarding with a shield.
Use the <PADM>left stick<KEYM>move key</KEYM> to dash in a specific direction.
<COL ffdc78>LV UP: Decreases Stamina cost to block.
LV.6: Able to dash left and right. Increases speed.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_16'
old = '''
素早く剣を突き、直後に引き抜く二段攻撃を放つ
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加</COL>'''
new = '''
Delivers a quick stab and withdrawal slash
without distancing user and target, allowing
for further blows thereafter.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_19'
old = '''
敵の攻撃を受け流しつつ剣を振り払って斬り抜ける
<PADM>左スティック<KEYM>移動キー</KEYM>により後方への斬り抜けも可能
攻撃を受ける瞬間に発動すると威力が上昇する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃範囲拡大／受付時間延長</COL>'''
new = '''
Hold your shield in wait, deflecting and seamlessly
countering enemy attacks. Use the <PADM>left stick<KEYM>move key</KEYM> to move
forward or back. Perfect blocks deal more damage.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases range. Increases counter duration.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_17'
old = '''
高威力の剣舞を広範囲に繰り出す
初段を敵に接触させれば連撃に移行する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６でモーション変化／攻撃ヒット数増加</COL>'''
new = '''
A high-powered sword dance that covers a wide area.
If the first hit is successfully landed, it will become a full on
combo attack.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Increases the number of hits in the attack, and changes
the motion of the skill.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_120'
old = '''
しがみついた状態から、力を溜めこみ豪快に切り払う
溜め中は敵の揺さぶりにも耐え、
ボタンの連打で威力が上昇する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加／必要入力回数減少</COL>'''
new = '''
While climbing an enemy, channel power into
a tremendous blow. While charging, you resist being shaken off
the enemy. The power of the attack rises with consecutive button
presses.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Increase the number of hits in the attack, and decrease
amount of button presses needed for a full charge.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_121'
old = '''
敵の攻撃の反動を利用し、斬りつけながら跳ね上がる
跳躍後、ボタンの追加入力で派生斬りを発動
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で跳び上がる高度上昇／
派生斬りの攻撃ヒット数増加</COL>'''
new = '''
Utilize an enemy attack to launch yourself, slashing upwards. 
After ascending, invert the direction of the slash with an additional button press.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Increase altitude of the launch, and number of hits of the inverted
slash.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_154'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
攻撃ヒット数が増加
チャンス攻力と疲労攻力がやや増加
<COL ff7878>人間／竜族／錬金系の敵に与えるダメージ量が増加</COL>'''
new = '''
EX Additional Effects:
Increase damage.
Increase number of hits.
Slightly increase chance attack and Fatigue attack.
<COL ff7878>Further increase damage to Human/Dragonkin/Alchemized type enemies.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_155'
old = '''
【ＥＸ追加効果】
前方への攻撃範囲が大幅に拡張
吹き飛ばし力が増加
ダメージ量がやや増加
チャンス攻力と疲労攻力がやや増加'''
new = '''
EX Additional Effects:
Extend the range of the attack.
Increase blow power.
Slightly increase damage.
Slightly increase chance attack and fatigue attack.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_174'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
吹き飛ばし力が増加
気絶攻力が増加'''
new = '''
EX Additional Effects:
Increase damage.
Increase blow force.
Increase knockout power.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_175'
old = '''
【ＥＸ追加効果】
ダメージ量がやや増加
チャンス攻力と疲労攻力が増加
攻撃範囲がやや拡張'''
new = '''
EX Additional Effects:
Slightly increase damage.
Increase chance attack and exhaust attack.
Slightly extend attack range'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_209'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
引き抜きの攻撃ヒット数が増加
ジャンプの飛距離が延長'''
new = '''
EX Additional Effects:
Increase number of hits when pulling your sword out.
Increase leaping distance.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_01_210'
old = '''
【ＥＸ追加効果】
空中で発動可能になる
吹き飛ばし力が増加
攻撃対象に密着した状態で空中で発動すると
対象を蹴ってより高くジャンプする'''
new = '''
EX Additional Effects:
Possible to activate in the air.
Increase blow force.
If activated near enemies, use them as steeping stones
and jump higher.'''

