[[message]]
key = 'CUSTOM_SKILL_INFO_02_20'
old = '''
敵を追従する猛ダッシュの斬りつけ攻撃を放つ
初撃が当たると連続で斬り返しを放つ
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で移動距離が延長／
斬り返し回数増加（１→３）</COL>'''
new = '''
Dashes past the target with blades extended, delivering
slashes that can be followed with further attacks on contact.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases moving distance.
Increases number of further attacks (1→3).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_21'
old = '''
一歩踏み込み、敵を上空へ斬り上げる
ボタンの追加入力で追撃する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加</COL>'''
new = '''
Steps in with a blade strike that sends
the target aloft. Additional button presses
throw and detonate a store of powder.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_24'
old = '''
瞬時に身を引き、すぐさま前方に蹴りを放つ
敵の攻撃を回避しつつ繰り出せば威力が上昇する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６でモーション変化／攻撃ヒット数増加</COL>'''
new = '''
Pulls back momentarily afore unleashing a
frontal kick. Using it as an evasive
maneuver increases its power.
<COL ffdc78>LV UP: Increases damage.
LV.6: Motion changes. Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_22'
old = '''
シーカーロープを投げて敵を捉え、
手前に引き寄せる
<COL ffdc78>LV UP毎に引き寄せる力の上昇
LV.６で攻撃範囲拡張/捕捉敵数増加（１→３）</COL>'''
new = '''
Casts out your seeker rope to snare lightweight foes,
pulling them to the ground to incapacitate them.
<COL ffdc78>LV UP: Increases the force of the pull.
LV.6: Increase range of the effect.
Increases total enemies affected (1→3).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_29'
old = '''
空中からシーカーロープを放って地面にひっかけ、
地上へ急降下攻撃を繰り出す。空中でも発動可能
高所から行うことで威力が上昇し気絶させやすくなる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で周囲の敵をのけぞらせることが可能</COL>'''
new = '''
Hook the ground with your seeker rope, performing
a dive attack towards the ground. A high altitude
will increase the power. Can be activated in the air.
<COL ffdc78>LV UP: Increases damage.
LV.6: Inflicts stagger on surrounding enemies.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_23'
old = '''
前方に飛び蹴りを繰り出し、敵を踏み台にして
上空へ跳び上がる
空中でも発動可能
<COL ffdc78>LV UP毎にジャンプ力上昇
LV.６で敵のガード状態を崩すことが可能</COL>'''
new = '''
Leaps forward in a flying kick, then uses the
target as a foothold to jump still higher.
Can be activated in the air.
<COL ffdc78>LV UP: Increases force of the jump.
LV.6: Breaks enemy guard.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_25'
old = '''
自身を通常の構え姿勢に戻し、様々な動作の
スキを消すことができる（連続では行えない）
空中でも発動可能
<COL ffdc78>LV UP毎に再発禁止時間が短縮
LV.６で拘束中を除きいつでも発動可能</COL>'''
new = '''
Returns the user to a neutral stance, eliminating
openings caused by other actions. Cannot be performed
continously. Can be activated in the air.
<COL ffdc78>LV UP: Reduces the restriction time between uses.
LV.6: Can be used anytime, except when restrained.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_26'
old = '''
地面に火薬を設置し、
遠方から導火線に着火して爆発させる
<COL ffdc78>LV UP毎に攻撃威力の上昇／仕込み時間短縮
LV.６で攻撃ヒット数増加／爆風に風圧追加</COL>'''
new = '''
Places an explosive on the ground to
be detonated from afar.
<COL ffdc78>LV UP: Increases damage. Decreases charge time.
LV.6: Increases number of hits.
Adds wind pressure to the blast.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_30'
old = '''
ダガーを高速回転させ、敵を巻き込み斬りつける
<PADM>左スティック<KEYM>移動キー</KEYM>で任意方向に移動できる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で移動距離が延長／攻撃ヒット数増加</COL>'''
new = '''
Rotate your daggers at high speed, slashing nearby
enemies. Use the <PADM>left stick<KEYM>move key</KEYM> to move while rotating.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases movement distance.
Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_31'
old = '''
シーカーロープを放って敵を捕らえ、反動を利用して
気絶を誘うスライディング攻撃を繰り出す
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で移動距離が延長</COL>'''
new = '''
Grapple the enemy with your seeker rope, staggering
them and sliding through with a sharp attack.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases movement distance.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_27'
old = '''
自身の体に炎をまとい触れた敵にダメージを与える
さらに武器の攻撃属性を炎にする
ただし、発動中は自身の体力が徐々に減少する
<COL ffdc78>LV UP毎に炎属性威力の上昇／体力減少速度軽減
LV.６で最大持続時間が延長</COL>'''
new = '''
Sets your body ablaze, inflicting damage to enemies
you touch and adds Fire attribute to your attacks.
However, your health will gradually drain during use.
<COL ffdc78>LV UP: Increases damage. Decreases health drain.
LV.6: Increases duration of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_28'
old = '''
敵の攻撃を受け流し、瞬時に背後に回り込んで
致命の一撃を与える
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加／受付時間延長／
攻撃アクション中であればいつでも発動可能</COL>'''
new = '''
If used to correctly parry an enemy's attack, 
instantly climb behind them, and deliver a lethal blow in response.
<COL ffdc78>LV UP: Increases number of hits in the counter.
LV.6: Extends counter window duration and can be activated anytime
during attacks.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_129'
old = '''
自身の周囲に火薬を撒き、
ダガーで弾いて爆発を起こす
空中でも発動可能
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加</COL>'''
new = '''
Sprinkle gunpowder all around and strike the daggers together,
causing an explosion.
Can be activated even while in the air.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Increases the number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_130'
old = '''
シーカーロープを放って敵を捕らえ、反動を利用して
激しく斬りこみながら距離を詰める
ボタン追加入力で追撃を繰り出す。空中でも発動可能
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加</COL>'''
new = '''
Throw the Seeker Rope to snag an enemy, using
the recoil to propel yourself towards them, and deliver deadly
slashes all along the way.
Additional button presses will chain the chase.
Can be activated even while in the air.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Increases the number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_160'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
気絶攻力が増加'''
new = '''
EX Additional Effects:
Increase damage.     
Increase knockout power.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_161'
old = '''
【ＥＸ追加効果】
空中で使用可能になる
チャンス攻力が増加
疲労攻力が増加'''
new = '''
EX Additional Effects:
Possible to activate in the air.    
Increase chance attack.
Increase fatigue power.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_158'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
<COL ff7878>獣／有翼／侵食系の敵に与えるダメージ量が増加</COL>'''
new = '''
EX Additional Effects:
Increase damage.
<COL ff7878>Further increase damage to Beast/Winged/Infected enemies.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_159'
old = '''
【ＥＸ追加効果】
空中使用回数が増加（１→２）
吹き飛ばし力がやや増加'''
new = '''
EX Additional Effects:
Increase the number of possible executions in air (1→2)'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_213'
old = '''
【ＥＸ追加効果】
空中発動時１度だけモーションが変化しダメージが追加
攻撃スキルを敵に接触させる／着地／しがみつきにより
カスタムスキルＥＸ追加効果を空中で再度発動可能'''
new = '''
EX Additional Effects:
Change motion only once when activate in the air and add damage.
This EX effect can be activated again in the air if you attack/climb/land.
'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_214'
old = '''
【ＥＸ追加効果】
発動時と跳び上がり時に敵の攻撃をすり抜ける
空中発動時に短剣による攻撃が追加'''
new = '''
EX Additional Effects:
Add invulnerability time when activated and jumping.
Add dagger attack when in the air.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_215'
old = '''
【ＥＸ追加効果】
モーションが変化し、短剣による攻撃回数が増加
爆発の攻撃ヒット数が増加'''
new = '''
EX Additional Effects:
Change motion, increase number of dagger attacks.
Increase number of explosion hits.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_216'
old = '''
【ＥＸ追加効果】
斬り上げと爆発の攻撃範囲が拡張
爆発に炎防低下の状態異常が付与され
延焼の状態異常蓄積値も増加'''
new = '''
EX Additional Effects:
Increase range of dagger slash and explosion.
Add Fire Resist Down accumulation to explosion hits.
Increase Burn accumulation.'''
