[[message]]
key = 'CUSTOM_SKILL_INFO_03_32'
old = '''
複数の矢を連続で放ち
敵を大きくのけぞらせる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で矢の発射数増加（３→５）</COL>'''
new = '''
Fire multiple arrows in quick succession.
Staggers large enemies.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases arrows fired (3→5).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_37'
old = '''
貫通力のある矢を放つ
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で貫通時のヒット間隔が短縮し
連続ヒットしやすくなる</COL>'''
new = '''
Fires a shot capable of piercing multiple targets.
<COL ffdc78>LV UP: Increases damage.
LV.6: Shortens the interval between hits,
increasing the likelihood of hitting more times.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_33'
old = '''
複数の矢を同時に扇状に放つ
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で矢の発射数増加（３→５）</COL>'''
new = '''
Fires three arrows in a wedge pattern.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases arrows fired (3→5).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_34'
old = '''
敵のガードを崩す爆音火薬を巻いた矢を放つ
爆音に巻き込むことで周囲の敵をも怯ませる
<COL ffdc78>LV UP毎に吹き飛ばし力の上昇
LV.６で攻撃範囲拡大</COL>'''
new = '''
Fires an arrow that produces a deafening
blare on impact, breaking enemy guard.
Will also launch nearby enemies.
<COL ffdc78>LV UP: Increases blow power.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_36'
old = '''
矢筒内のすべての矢を直上に放ち、
敵の頭上に降らせる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加</COL>'''
new = '''
Sends a wall of arrows skyward to
rain down on a broad area.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_38'
old = '''
着弾時に回転し多段攻撃を加える矢を放つ
特に状態異常矢の使用時に効果的
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加</COL>'''
new = '''
Looses a spinning arrow that delivers a
barrage of hits to an area.
Especially effective with status arrows.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_39'
old = '''
装填中のすべての矢に気絶効果のある火薬を
巻きつけ強化する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃範囲拡大</COL>'''
new = '''
Applies an explosive stun effect to all
arrows loaded. Increases damage inflicted.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_35'
old = '''
渾身の力で弓を引き、高威力の矢を放つ
溜め満了の瞬間に矢を放つと威力が
大幅に上昇する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で溜め段階拡張（１→２）</COL>'''
new = '''
Draws the bow with all the user's might,
then looses a shot straight ahead.
Power greatly increases if released as
maximum charge is reached.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases total charge stages (1→2).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_42'
old = '''
素早く後方に移動する
敵との間合いを素早く離す
<COL ffdc78>LV UP毎にスタミナ消費減少／発動中の耐久力上昇
LV.６でモーション変化／すり抜け時間延長</COL>'''
new = '''
Quickly dodges backwards, creating distance
between you and your enemies.
<COL ffdc78>LV UP: Decreases Stamina cost.
Increases Endurance during usage.
LV.6: Motion changes. Increases invulnerability time.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_40'
old = '''
火薬を巻きつけた複数の矢を、
渾身の力で空に放ち、敵の頭上に降らせる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で矢の発射数増加（３→５）</COL>'''
new = '''
Coat multiple arrows in gunpowder and send them
skyward to rain down on a broad area.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases arrows fired (3→5).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_41'
old = '''
ボタンの連打で射撃回数が増加する
また、射撃回数が増えるにつれ
敵を怯ませやすくなる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃速度上昇</COL>'''
new = '''
Continously shoot multiple arrows as you press
the button. As you shoot more arrows, it becomes
easier to stagger enemies.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases attack speed.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_43'
old = '''
絶大な威力の矢を放つ。溜め満了の瞬間に放つと
威力が大幅に上昇し、残り体力が低い敵ほど
効果が高い
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で溜め時間短縮</COL>'''
new = '''
Draw the bow back with all your might and loose an arrow
of extraordinary power. Further increase damage if fired just as the charge is
completed. The lower the enemy's health, the higher the damage of this skill.
<COL ff7878>Effective against War-Ready enemies.</COL>
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Decreases charge time.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_131'
old = '''
連鎖的に爆発する火薬を巻きつけた矢を
上空に放つ
射撃時にボタン長押しで起爆高度が上昇
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で爆発回数増加</COL>'''
new = '''
Loose an arrow wrapped with explosive powder into
the sky. Detonation altitude rises the longer the button is held
while firing.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Increases the number of explosions.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_132'
old = '''
敵に密着し、矢筒内の矢を全て番えて渾身の力で放つ
しがみつき状態からでも可能
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で溜め段階上昇（２→３）
ボタン入力回数減少</COL>'''
new = '''
Tightly bind together all the arrows in the quiver,
and unleash them with your entire body's might.
Can be activated while climbing an enemy.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Increases maximum charge (2→3) and reduces number of button presses
needed to advance to the next level of charge.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_162'
old = '''
【ＥＸ追加効果】
発射数が増加（５→６）
連なり射ち 剛に付与した紅蓮爆矢の攻撃威力が上昇'''
new = '''
EX Additional Effects:
Increase the number of arrows shot (5→6).
Further increase the damage and blow power when
using in conjuction with Crimson Arrow.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_163'
old = '''
【ＥＸ追加効果】
構え中の移動速度が上昇
最適距離の範囲が拡張
射程距離が延長'''
new = '''
EX Additional Effects:
Increase moving speed during bow stance.
Extend the optimal shooting range.
Extend the shooting range.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_164'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
状態異常値が増加
<COL ff7878>獣／有翼／侵食系の敵に与えるダメージ量が増加</COL>'''
new = '''
EX Additional Effects:
Increase damage.
Increase debilitation rate.
<COL ff7878>Further increase damage to Beast/Winged/Infected enemies.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_165'
old = '''
【ＥＸ追加効果】
チャンス攻力と疲労攻力が増加
気絶攻力が増加
<COL ff7878>戦甲を攻撃時、ダメージ量が増加</COL>'''
new = '''
EX Additional Effects:
Increase chance attack and exhaust power.
Increase knockout power.
<COL ff7878>Further increase damage against War-Ready enemies.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_197'
old = '''
【ＥＸ追加効果】
攻撃ヒット数が増加'''
new = '''
EX Additional Effects:
Increase number of hits.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_03_198'
old = '''
【ＥＸ追加効果】
構え中の移動速度が上昇
最適距離の範囲が拡張
射程距離が延長'''
new = '''
EX Additional Effects:
Increase moving speed during bow stance.
Extend the optimal shooting range.
Extend the shooting range.'''