[[message]]
key = 'CUSTOM_SKILL_INFO_05_56'
old = '''
大盾に一定時間、敵の攻撃を防いだ瞬間に
衝撃波を放つ効果を付与する
<COL ffdc78>LV UP毎に効果持続時間延長
LV.６で攻撃威力の上昇</COL>'''
new = '''
For a period of time, when an attack is blocked,
a shockwave will be emitted.
<COL ffdc78>LV UP: Increases duration of the effect.
LV.6: Increases damage.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_58'
old = '''
ロッドの放射光を敵に照らしつづけることで
敵に遅延の状態異常値を蓄積させる
フォースゲージ１本以上の時、消費して技性能上昇
<COL ffdc78>LV UP毎に遅延の異常値上昇
LV.６で照射範囲拡大</COL>'''
new = '''
Channel a light from your rod towards the enemy.
Slowly accumulates the Torpor debilitation over time.
With more than 1 Force Gauge, the effect will increase.
<COL ffdc78>LV UP: Increases the rate of Torpor accumulation.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_59'
old = '''
ロッドの放射光を敵に照らしつづけることで
敵に睡眠の状態異常値を蓄積させる
フォースゲージ１本以上の時、消費して技性能上昇
<COL ffdc78>LV UP毎に睡眠の異常値上昇
LV.６で照射範囲拡大</COL>'''
new = '''
Channel a light from your rod towards the enemy.
Slowly accumulates the Sleep debilitation over time.
With more than 1 Force Gauge, the effect will increase.
<COL ffdc78>LV UP: Increases the rate of Sleep accumulation.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_60'
old = '''
大盾を構え前方に突進し、進行線上の敵を吹き飛ばす
フォースゲージ１本以上の時、消費して技性能上昇
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で移動距離上昇／ヒット数増加</COL>'''
new = '''
Rush forward with your greatshield, blowing away enemies.
With more than 1 Force Gauge, the effect will increase.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases moving distance and number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_62'
old = '''
属性ダメージと異常値の軽減効果を味方に付与する
（ロッドに付与した炎・氷・雷・聖・闇のいずれか）
フォースゲージ１本以上の時、消費して時間大幅延長
<COL ffdc78>LV UP毎に持続時間延長／軽減値上昇
LV.６で効果範囲拡大</COL>'''
new = '''
Decreases attribute damage taken and debilitation build-up
for nearby allies. (Determined by element granted to rod)
With more than 1 Force Gauge, the duration will increase.
<COL ffdc78>LV UP: Increases duration and power of the effect.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_61'
old = '''
地を揺らし、広範囲の敵をよろめかせる
大型の敵や一部の強敵には無効
フォースゲージ１本以上の時、消費して詠唱時間短縮
<COL ffdc78>LV UP毎に詠唱時間短縮
LV.６で攻撃範囲拡大</COL>'''
new = '''
Shake the earth, staggering enemies in a
wide range. Staggers large enemies and
some formidable foes.
フォースゲージ１本以上の時、消費して詠唱時間短縮
<COL ffdc78>LV UP: Shortens casting time.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_63'
old = '''
魔法のアンカーを射出し、敵を一定時間拘束する
大型の敵や一部の強敵には、物攻低下・魔攻低下・
物防低下・魔防低下の状態異常値を蓄積させる
<COL ffdc78>LV UP毎に拘束中スタミナ消費減少／状態異常値上昇
LV.６で射程距離延長</COL>'''
new = '''
Use magick to create an anchor, binding the enemy.
Inflicts ATK Down, MATK Down, and slowly builds
DEF Down, MDEF Down to large and some formidable enemies.
<COL ffdc78>LV UP: Decrease Stamina cost. Increase Debilitation rate.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_57'
old = '''
大盾に広範囲を防御できる魔法の壁を付加する
<COL ffdc78>LV UP毎に効果持続時間延長
LV.６で防御範囲が全方位化</COL>'''
new = '''
Create walls of magick that increase the range
of your shield's ability to block.
<COL ffdc78>LV UP: Increases duration of the effect.
LV.6: Makes the effect protect all of your sides.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_65'
old = '''
属性防御の低下異常値を敵に蓄積させる放射光を放つ
（ロッドに付与した炎・氷・雷・聖・闇のいずれか）
フォースゲージ１本以上の時、消費して技性能上昇
<COL ffdc78>LV UP毎に選択中属性の異常値上昇
LV.６で照射範囲拡大</COL>'''
new = '''
Channel a light from your rod towards the enemy.
Slowly accumulates a debilitation that decreases attribute
defense of enemies. (Determined by element granted to rod)
<COL ffdc78>LV UP: Increases the rate of debilitation accumulation.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_66'
old = '''
大盾で敵の攻撃を弾き返し、敵に気絶の
状態異常値を蓄積させる衝撃を与える
フォースゲージ１本以上の時、消費して技性能上昇
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で受付時間延長</COL>'''
new = '''
Deflect enemy attacks with your greatshield, stunning them.
The impact will accumulate debilitations on enemies.
With more than 1 Force Gauge, the effect will increase.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases the duration of the counter stance.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_64'
old = '''
法力で守護された空間を発現し、
空間内にいる味方へのダメージを無効化する
<COL ffdc78>LV UP毎に詠唱時間短縮
LV.６で展開エリアのサイズ拡張</COL>'''
new = '''
Guard an area around you,
nullifying damage for all allies nearby.
<COL ffdc78>LV UP: Shortens casting time.
LV.6: Increases the size of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_67'
old = '''
魔法のアンカーを射出し、捕らえた敵から攻力を
吸収することでフォースゲージを溜める
ヒット中、<PADM>左スティック<KEYM>移動キー</KEYM>で任意方向へ移動可能
<COL ffdc78>LV UP毎にヒット中のスタミナ消費減少
LV.６で射程距離延長</COL>'''
new = '''
Fire a magickal anchor towards a foe, and gradually
fill the force gauge and aggression meter if it hits.
While the anchor is active, you can move in any direction
with <PADM>the left stick.<KEYM>the movement keys.</KEYM>
<COL ffdc78>LV UP: Decreases stamina consumption for each additional
hit while the anchor is active.
LV.6: Increases range of the skill.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_136'
old = '''
ロッドの放射光を敵に照らしつづけることで
敵に石化の状態異常値を蓄積させる
フォースゲージ１本以上の時、消費して技性能上昇
<COL ffdc78>LV UP毎に石化の異常値上昇
LV.６で照射範囲拡大</COL>'''
new = '''
Keep the rod focused on an enemy, and radiate a light that
builds up the Petrified status abnormality on them.
When the Force Gauge has one or more charges, they will be
automatically consumed to increase the skill's performance.
<COL ffdc78>LV UP: Increases Petrified status accumulation.
LV.6: Increases the range of the light.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_135'
old = '''
周囲の敵を巻きこみながら大盾を振り払う
敵の攻撃を防ぎながら発動で威力が上昇
フォースゲージ１本以上の時、消費して技性能上昇
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で盾ガード値上昇／ヒット数増加</COL>'''
new = '''
Shake the Greatshield about while running around enemies,
preventing their attacks and increasing aggression.
When the Force Gauge has one or more charges, they will be
automatically consumed to increase the skill's performance.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Increases Guard Power and number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_170'
old = '''
【ＥＸ追加効果】
岩石を吹き飛ばし、ダメージを与える
<COL ff7878>戦甲を攻撃時、ダメージ量が増加</COL>'''
new = '''
EX Additional Effects:
Blow off the rocks from earth and deal damage to enemies.
Increase damage agaisnt War-ready enemies.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_171'
old = '''
【ＥＸ追加効果】
周囲の敵の注目を素早く集める
エンチャントが付与されている際は
エンチャント属性の状態異常を発生させることも可能'''
new = '''
EX Additional Effects:
Attract enemies within the area.
Cause status abnormality of the currently enchanted element
of your weapon.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_172'
old = '''
【ＥＸ追加効果】
詠唱速度が上昇
ダメージ量が増加
ガードブレイク性能を持つ攻撃もガード可能'''
new = '''
EX Additional Effects:
Increase casting speed.
Increase damage.
Possible to block guard-break attacks.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_173'
old = '''
【ＥＸ追加効果】
発動中は攻力吸収量が増加
敵を引き付けて攻撃を防御するとスタミナが回復'''
new = '''
EX Additional Effects:
Increase Force Gauge gained by blocking.
Restore stamina when blocking attacks
and attracting enemies.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_205'
old = '''
【ＥＸ追加効果】
ダメージ量と気絶攻力が増加
フォースゲージ消費時に威力が上昇／ヒット数増加
<COL ff7878>造魔／魔族／戦甲系の敵に与えるダメージ量が増加</COL>'''
new = '''
EX Additional Effects:
Increase damage and knockout power.
Further increase damage and number of hits
when a Force Gauge is consumed.
<COL ff7878> Further increase damage against Construct/Demon/War-Ready type enemies.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_206'
old = '''
【ＥＸ追加効果】
スキル発動中ガード状態になる
敵の攻撃を防いだ後、攻撃を敵に接触させる度に
フォースゲージが増加する'''
new = '''
EX Additional Effects:
Guard yourself during execution.
After blocking an enemy's attack,
Force Gauge increases with every hit.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_207'
old = '''
【ＥＸ追加効果】
詠唱時間短縮
展開中に魔法の壁を解放して聖属性の攻撃が可能
敵の攻撃を防ぐと魔法の壁のエネルギーが蓄積し
解放時のダメージ量が増加する'''
new = '''
EX Additional Effects:
Reduce charge time.
Can release magick wall and attack surrounding enemies.
Blocking attacks will accumulate the energy of the wall,
increasing damage.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_05_208'
old = '''
【ＥＸ追加効果】
展開中、物理防御力／魔法防御力／耐久力が増加'''
new = '''
EX Additional Effects:
Increase Physical/Magick defense and Endurance.'''