[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_80'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_82'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_81'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_83'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_84'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_85'
old = 'セットボタン押しっぱなし'
new = 'Hold the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_87'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_86'
old = '敵の攻撃を引きつけてセットボタンを押す'
new = '''
Just as an enemy attacks,
press the assigned button.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_90'
old = '敵の攻撃を引きつけてセットボタンを押す'
new = '''
Just as an enemy attacks,
press the assigned button.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_89'
old = 'セットボタンを連続して押す'
new = 'Repeatedly press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_91'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_88'
old = '''
セットボタン押しっぱなし
<COL ff7878>溜め満了で戦甲へのカウンターに特化</COL>'''
# NEEDS REVIEW
new = '''Hold the assigned button.
<COL ff7878>Effective against War-Ready enemies if this skill is executed
at full gauge.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_139'
old = 'しがみつき中にセットボタンを押す'
new = '''
While climbing an enemy,
press the assigned button.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_140'
old = '''
セットボタン押しっぱなし
空中ではセットボタンを押す'''
new = '''
Hold the assigned button.
While in the air, press the assigned button.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_180'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_181'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_182'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_183'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_225'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_226'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_227'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_07_228'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
