[[message]]
key = 'CUSTOM_SKILL_INFO_08_95'
old = '''
氷属性の複数の魔矢を一点に集中して放つ
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で魔矢の本数増加（４→６）</COL>'''
new = '''
Fire multiple magickal arrows with
the Ice attribute at a single point.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases magickal arrows fired (4→6).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_92'
old = '''
魔矢を放ち、着弾地点に体力回復効果のある
魔法球を展開する（対不死には攻撃）
味方に接触させれば魔法球が吸着する
<COL ffdc78>LV UP毎に回復力上昇／展開エリア拡張
LV.６でターゲット数増加（２→４）</COL>'''
new = '''
Fire magickal arrows that emit an area of health
restoration at the impact point. (Inflicts damage to undead)
The field will attach to an ally if the arrow makes contact.
<COL ffdc78>LV UP: Increases healing power. Increases size of the effect.
LV.6: Increases number of targets (2→4).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_93'
old = '''
魔矢を放ち、着弾地点に一部の状態異常回復効果
のある魔法球を展開する（対不死には攻撃）
味方に接触させれば魔法球が吸着する
<COL ffdc78>LV UP毎にスタミナ消費減少
LV.６でターゲット数増加（２→３）</COL>'''
new = '''
Fire magickal arrows that emit an area of debilitation
recovery at the impact point. (Inflicts damage to undead)
The field will attach to an ally if the arrow makes contact.
<COL ffdc78>LV UP: Reduces Stamina cost.
LV.6: Increases number of targets (2→3).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_94'
old = '''
起爆性のある魔矢を放つ
敵に刺さった魔矢への攻撃には爆発がともなう
爆発に接触した周囲の敵は中心地に吹き飛ぶ
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で爆発範囲が拡張</COL>'''
new = '''
Loose a magickal arrow that attaches to enemies.
Upon attacking the magickal arrow, it will trigger an explosion.
Enemies in contact with the explosion will be knocked away.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases the range of the explosions.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_97'
old = '''
聖属性の魔矢を放ち、着弾場所に魔法球を
展開する。敵に接触させた場合魔法球が付着し
継続して体力を奪う
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で魔法球継続時間が延長／攻撃ヒット数増加</COL>'''
new = '''
Fire magickal arrows of the Holy attribute. The arrows 
will emit a magickal sphere upon impact. Enemies in
contact with the sphere will continously take damage.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases duration of spheres. Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_98'
old = '''
敵の物理攻撃力と魔法攻撃力を
一定時間低下させる魔矢を放つ
<COL ffdc78>LV UP毎に低下力の強化
LV.６でターゲット数増加（３→５）</COL>'''
new = '''
Fire magickal arrows that decrease the
Physical and Magickal attack power of
enemies for a period of time.
<COL ffdc78>LV UP: Increases the rate of debilitation accumulation.
LV.6: Increases number of targets (3→5).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_99'
old = '''
敵の物理防御力と魔法防御力を
一定時間低下させる魔矢を放つ
<COL ffdc78>LV UP毎に低下力の強化
LV.６でターゲット数増加（３→５）</COL>'''
new = '''
Fire magickal arrows that decrease the
Physical and Magickal defense of
enemies for a period of time.
<COL ffdc78>LV UP: Increases the rate of debilitation accumulation.
LV.6: Increases number of targets (3→5).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_96'
old = '''
壁に反射し、敵を追従する雷属性の魔矢を放つ
反射させる度に威力が上昇する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で反射回数が増加</COL>'''
new = '''
Loose a magickal arrow that increases in
power as it ricochets towards its target.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases the number of ricochets.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_100'
old = '''
魔矢を放ち、着弾地点にスタミナ回復効果のある
魔法球を展開する。味方に接触させれば魔法球が
吸着する（対不死には攻撃）
<COL ffdc78>LV UP毎に魔法球継続時間の延長／展開エリア拡張
LV.６で魔力増加速度の上昇</COL>'''
new = '''
Fire magickal arrows that emit an area of Stamina
restoration at the impact point. (Inflicts damage to undead)
The field will attach to an ally if the arrow makes contact.
<COL ffdc78>LV UP: Increases duration. Increases size of the effect.
LV.6: Increases casting speed.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_101'
old = '''
敵の耐久力を一定時間低下させる魔矢を放つ
<COL ffdc78>LV UP毎に低下力の強化
LV.６で魔力増加速度の上昇／
ターゲット数増加（５→７）</COL>'''
new = '''
Fire magickal arrows that decrease the
Endurance of enemies for a period of time.
<COL ffdc78>LV UP: Increases the rate of debilitation accumulation.
LV.6: Increases casting speed.
Increases number of targets (5→7).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_102'
old = '''
怒り中の敵のシークレットコアにのみ有効な魔矢
攻撃を加えることで敵スタミナを大幅に低下させる
魔法球を展開する。コアは構え中に発見可能
<COL ffdc78>LV UP毎に低下力の強化
LV.６で魔法球継続時間が延長</COL>'''
new = '''
Loose a magickal arrow that attaches to revealed
weakpoints of enemies and forms a sphere. Greatly
decreases the Stamina of enemies when attacked.
<COL ffdc78>LV UP: Increases the stamina reduction.
LV.6: Increases the duration of the sphere.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_103'
old = '''
魔力を十分に溜めた後、特大威力の聖属性魔矢を放つ
<PADM>左スティック<KEYM>移動キー</KEYM>で軌道操作可能。威力はスタミナ依存
なお当たった部位は暫く自動的に魔矢の標的になる
<COL ffdc78>LV UP毎に攻撃威力／魔力増加速度の上昇
LV.６で攻撃ヒット数増加</COL>'''
new = '''
After gathering sufficient magickal power, let loose
an extraordinarily powerful Holy arrow.
The arrow can be controlled mid-flight with the <PADM>Left Stick<KEYM>Movement Keys</KEYM>.
The power of the skill depends on the stamina available.
The hit spot will automatically be targeted by the magickal
arrows for a while.
<COL ffdc78>LV UP: Increases damage and cast speed of the skill.
LV.6: Increases number of hits.</COL>
'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_141'
old = '''
癒しの力を込めた魔矢を放ち、上空で起爆させる
矢は起爆時に強い光を放ち、照らされた味方の
体力を一定量回復する（対不死には攻撃）
<COL ffdc78>LV UP毎に回復量上昇
LV.６で起爆時の閃光効果強化</COL>'''
new = '''
Let loose a holy magickal arrow imbued with the power to heal
into the sky and detonate it. The arrow emits a strong flash at
the time of detonation, recovering a portion of health for allies.
(Damages Undead)
<COL ffdc78>LV UP: Increases health recovery amount.
LV.6: Increases the power of the flash at detonation.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_142'
#NEEDS REVIEW
#魔矢を放ち、接触した敵を内側から引き裂く触手を
#発生させる。触手は他の攻撃対象を感知し、
#自ら攻撃に向かう。侵食核の破壊に有効
#<COL ffdc78>LV UP毎に攻撃威力の上昇
#LV.６で連鎖回数増加</COL>
old = '''
魔矢を放ち、接触した敵を引き裂く触手を発生させる
触手は攻撃対象を自ら追尾し、攻撃が連鎖する
連鎖回数は敵の大きさで変動。侵食核の破壊に有効
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で連鎖回数増加</COL>'''
new = '''
Let loose a magickal arrow that tears apart the enemy it contacts
with tentacles. The tentacles will seek out additional enemies or
continue to attack current target depending on its size. 
Effective for destroying Infected Sprouts.
<COL ffdc78>LV UP: Increases damage of skill.
LV.6: Increases the target chain amount.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_184'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
魔矢が刺さった敵の体力を継続して奪う'''
new = '''
EX Additional Effects:
Increase damage.
Continuously cause damage at the point the arrow landed.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_185'
old = '''
【ＥＸ追加効果】
魔矢が刺さった敵へ攻撃した際の
状態異常値を増加させる'''
new = '''
EX Additional Effects:
Increase status effect accumulation when attacking enemies hit by
this skill.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_186'
old = '''
【ＥＸ追加効果】
ダメージが追加
吹き飛ばし力が増加
魔矢の速度が上昇'''
new = '''
EX Additional Effects:
Add damage to the skill.
Increase blow force.
Increase arrow's speed.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_187'
old = '''
【ＥＸ追加効果】
ダメージが追加
封印の状態異常を付与／気絶攻力が増加
魔矢の速度が上昇'''
new = '''
EX Additional Effects:
Add damage to the skill.
Add Skill Stiffling status abnormality
and knockout power.
Increase arrow's speed.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_201'
old = '''
【ＥＸ追加効果】
HP回復量アップ
<COL ff7878>骸骨／腐死／呪詛／霊体系の敵へ
与えるダメージ量と攻撃ヒット数増加</COL>'''
new = '''
EX Additional Effects:
Increase the amount of health recovered.
<COL ff7878>Increase damage and number of hits against
Skeleton/Undead/Cursed/Spirit type enemies</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_202'
old = '''
【ＥＸ追加効果】
治癒上限値を回復する
シークレットコア露出時間／触芽封印時間／
戦甲の修復停止時間が延長'''
new = '''
EX Additional Effects:
Recover healable limit of affected allies.
Increase duration of Secret Core reveal, Infected seal and
War-Ready Armor reveal.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_203'
old = '''
【EX追加効果】
闇属性のダメージが追加
溜め時間短縮
ターゲット数増加（５→７）'''
new = '''
EX Additional Effects:
Add Dark-attribute damage.
Reduce charge time.
Increase the number of target locks (5→7).'''
[[message]]
key = 'CUSTOM_SKILL_INFO_08_204'
old = '''
【EX追加効果】
最適距離の範囲が拡張
魔道弓に付与されている属性の
防御力を低下させる状態異常を付与'''
new = '''
EX Additional Effects:
Extend the optimal range.
Add Elemental Resist Down accumulation that matches your
weapon's element.
'''