[[message]]
key = 'CUSTOM_SKILL_INFO_11_237'
old = '''
聖属性の魔力を付与した剣で、周囲を薙ぎ払う
魔印が最大に成長している時、性能上昇
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.6で空中でも発動可能</COL>'''
new = '''
Imbue your sword with Holy attribute and
attack surrounding enemies.
Damage increases when the Magick Glyph grows.
<COL ffdc78>LV UP Increases damage of skill.
LV.6 Can be activated in the air.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_11_241'
old = '''
幻影を作り出し、前方へ瞬間移動する魔法
移動中に接触した敵に対して、魔力の斬撃を浴びせる
空中での連続発動は2回まで可能
<COL ffdc78>LV UP毎に再発動禁止時間が短縮
LV.6で攻撃アクション中であればいつでも発動可能</COL>'''
new = '''
Create a phantom and teleport forward.
If user comes into contact with enemy
while teleporting, deal magick damage.
Can use twice while mid air.
<COL ffdc78>LV UP Reduce cooldown between activation.
LV.6 Can be used at any time during attack.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_11_244'
old = '''
その場で剣を構え、振り下ろすと同時に
前方に複数の魔力の刃を放つ
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.6で攻撃ヒット回数が増加</COL>'''
new = '''
Ready your sword and slice downwards, releases several
magick blades towards enemies infont of you.
<COL ffdc78>LV UP Increases damage of skill.
LV.6 Increases number of hit.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_11_240'
old = '''
闇属性の魔力を付与した剣で
逆手に敵を突き、直後に引き抜く
魔印が最大に成長している時、性能上昇
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.6でしがみつき中でも発動可能</COL>'''
new = '''
Thrusts the blade imbued with dark magick into
the target's body before pulling it out.
Damage is increased when the Magick Glyph grows.
<COL ffdc78>LV UP Increases damage of skill.
LV.6 Can be used when climbing.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_11_238'
#NEEDS REVIEW
#自身の前方に魔力の盾を一定時間展開する
#<COL ffdc78>LV UP毎に展開時間延長
#LV.6で敵の攻撃に合わせて発動した際、展開時間延長</COL>
old = '''
自身の前方に魔力の盾を一定時間展開する
純魔法発動時は展開時間が減少しない
<COL ffdc78>LV UP毎に展開時間延長
LV.6で敵の攻撃に合わせて発動した際、展開時間延長</COL>'''
new = '''
Create a magickal barrier in front of you for a certain amount of
time. Barrier duration does not decrease when using pure magick.
<COL ffdc78>LV UP: Increases duration of the barrier.
LV.6 When invoked just before an enemy's attack connects,
duration is further increased.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_11_242'
old = '''
魔力の刃を敵に撃ち込み
闇・斬属性による継続ダメージを与える
ボタンの追加入力で攻撃ヒット数が増加
<COL ffdc78>LV UP毎に攻撃威力の上昇
Lv.6で追加入力時の攻撃ヒット数増加</COL>'''
new = '''
Bombard an enemy with Magick Blade, dealing continuous
Dark and Slash damage to enemy.
Number of hits increases with consecutive button presses.
<COL ffdc78>LV UP Increases damage of skill.
Lv.6 Increases number of hits with consecutive button presses.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_11_239'
old = '''
魔力を収束させ、聖・打属性の魔力の渦を発生させる
<COL ffdc78>LV UP毎に攻撃威力の上昇
Lv.6で攻撃ヒット回数が増加</COL>'''
new = '''
Create a vortex that deals Holy and Impact damage.
<COL ffdc78>LV UP Increases damage of skill
Lv.6 Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_11_243'
old = '''
刃に魔力を帯び、ノーマルスキルの剣技に残像を追加する
ボタン再入力で、残像の攻撃回数に応じて強化された
魔力吸収特化の一撃を放つ。発動中は魔力を消費し続ける
<COL ffdc78>LV UP毎に発動中の魔力消費量が減少
LV.6で再入力時の攻撃回数による強化段階が増加（１→２）'''
new = '''
Imbue magickal power on your sword, adding afterimage to the
core sword skills. Press the assigned button again to release
an attack that absorbs an amount of magick based on the number
of afterimage attacks. Slowly drain magick during activation.
<COL ffdc78>LV UP Reduces magick drain during activation.
Lv.6 Increases maximum number of charges from attacks (1→2).</COL>'''