[[message]]
key = 'CUSTOM_SKILL_INFO_10_143'
old = '''
斬り上げながら敵を打ち上げる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６でボタンの追加入力により派生斬りが発動</COL>'''
new = '''
Launch enemies upward with a slash.
<COL ffdc78>LV UP: Increases damage of skill.
LV.6: Invert direction of slash with an additional
button press.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_144'
old = '''
槍を振り払い、周囲を巻き込みながら攻撃する
空中発動可能
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６でのけぞり、吹き飛び中でも発動可能</COL>'''
new = '''
Swing the lance around, and attack
the surrounding area. Can be used in mid-air.
<COL ffdc78>LV UP: Increases damage of skill.
LV.6: Can be used while taking damage, and even while
being knocked off an enemy.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_146'
old = '''
力を溜めて離れた敵を攻撃する
初段がヒットすることで連続ヒットする追撃が発生
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で溜め段階拡張（１→２）</COL>'''
new = '''
Gather energy and thrust forward,
releasing a blast of energy. The first strike always
chases an enemy.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6:Increases number of hits (1→2).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_149'
old = '''
体力回復と防御力上昇効果の霊力エリアを展開する
エリアに接触した味方へ一定時間効果を付与
<COL ffdc78>LV UP毎に効果時間延長
LV.６で展開エリアの設置時間延長</COL>'''
new = '''
Form a pool of spiritual energy that
recovers health and grants allies whom walk into it
a Defense boost for a period of time.
<COL ffdc78>LV UP: Increases duration of effect.
LV.6: Increases duration of pool.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_145'
old = '''
前方に連続して攻撃を繰り出す
攻撃回数によって最後の一撃の威力が変化する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で最大攻撃回数増加</COL>'''
new = '''
Spin the lance all-around, continuously slashing
forward. The last blow's power changes according to the number of 
attacks made.
<COL ffdc78>LV UP: Increases damage of skill.
LV.6: Increases maximum number of attacks.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_147'
old = '''
攻撃すると衝撃波が発生する霊球を発現する
霊球は攻撃を受けることで霊力が溜まり
起爆することも可能／起爆は空中発動可能
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で霊力最大の起爆ヒット数増加／溜まる霊力増加</COL> '''
new = '''
Form a spirit orb that generates shockwaves
when attacked. The orb gathers spiritual energy when attacked.
It can also be detonated both on the ground and mid-air manually.
<COL ffdc78>LV UP: Increases damage of skill.
LV.6: Increases maximum hits of the detonation and amount of
spirit energy gained.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_150'
old = '''
自身を中心に体力回復と状態異常回復の霊球を展開
溜め時間に応じて範囲が拡大し
最大範囲になることで性能が上昇する
<COL ffdc78>LV UP毎に展開時間延長
LV.６で展開エリアの最大サイズが拡張</COL>'''
new = '''
Form spiritual spheres around yourself that
recovers health and status abnormalities. The range grows depending
on the charge time. The effectiveness of the skill rises upon a full
charge.
<COL ffdc78>LV UP: Increases duration of skill.
LV.6: Increases the area of effect of the skill.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_148'
old = '''
敵の攻撃を防ぐバリアを発現する。展開中に敵を攻撃すると
バリアに霊力が溜まり、セットボタンで霊力を使って攻撃可能
しがみつき状態から攻撃発動可
<COL ffdc78>LV UP毎に攻撃威力の上昇／バリア展開時間延長
LV.６でバリアの耐久値増加（１→２）</COL>'''
new = '''
Form a barrier around yourself to prevent
enemy attacks. When attacking enemies while the barrier is active,
spiritual energy gathers in the barrier. You can unleash the energy
by pressing the assigned button.
<COL ff7878>Effective against War-Ready enemies.</COL>
<COL ffdc78>LV UP: Increases damage of skill and duration.
LV.6: Increase maximum barrier durability (1→2)</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_153'
old = '''
強力な攻撃を広範囲に繰り出す
初段を敵に接触させれば連撃に移行する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６でモーション変化／攻撃ヒット数増加</COL>'''
new = '''
A high power skill that covers a wide area.
If the first hit is successfully landed, it will become a full on
combo attack.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Increases the number of hits in the attack, and changes
the motion of the skill.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_188'
old = '''
クレストを含むエンチャント攻撃力と吹き飛ばし力を
増加する霊力エリアを展開。攻撃を受け流し発動すると
展開サイズを拡張しつつ自身の強化性能を更に上昇させる
<COL ffdc78>LV UP毎に効果時間延長
LV.６でエンチャント強化と吹き飛ばし力強化の性能上昇</COL>'''
new = '''
Expand a spiritual area that increases damage and
blow force of enchantment of nearby allies including enchantment
from crests. If used as a counter, the effect is greatly increased
and the deployment size is expanded.
<COL ffdc78>LV UP: Increases duration of effect.
LV.6: Increases the effectiveness of the buff.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_195'
old = '''
【ＥＸ追加効果】
防御力の上昇量が増加
ヒールブースト時の攻撃力の上昇量が増加'''
new = '''
EX Additional Effects:
Increase defense buff value.
Increase attack buff value during Heal Boost.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_196'
old = '''
【ＥＸ追加効果】
攻撃を敵に接触させると
スタミナが回復する効果を付与
霊球の展開時間と効果時間が延長'''
new = '''
EX Additional Effects:
Recover stamina when attacking enemies.
Extend the duration of the pool.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_193'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
<COL ff7878>造魔／魔族／戦甲系の敵に与えるダメージ量が増加</COL>'''
new = '''
EX Additional Effects:
Increase damage.
<COL ff7878>Further increase damage to Construct/Demon/War-Ready enemies.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_194'
old = '''
【ＥＸ追加効果】
派生斬りを初段経由せずに空中で発動可能
スピリットゲージ蓄積量が増加'''
new = '''
EX Additional Effects:
Possible to activate in the air without executing the first hit.
Increase Spirit Gauge accumulation.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_233'
old = '''
【ＥＸ追加効果】
溜め満了の瞬間に攻撃を放つと威力が上昇する'''
new = '''
EX Additional Effects:
Increase damage if you release the attack
just as the charge is completed.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_10_234'
old = '''
【ＥＸ追加効果】
攻撃が最初にヒットした敵に
エイド／エイド・モールを吸着させる'''
new = '''
EX Additional Effects:
Attach an Aid/Aid More sphere at the impact point.'''