[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_8'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_12'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_10'
old = 'セットボタンを連続して押す'
new = 'Repeatedly press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_13'
old = 'セットボタンを連続して押す'
new = 'Repeatedly press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_15'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_9'
old = '''
セットボタンを押す
<COL ff7878>威力が最大となる高度からの攻撃で
戦甲へのカウンターに特化</COL> '''
# NEEDS REVIEW
new = '''Press the assigned button.
<COL ff7878>Effective against War-Ready enemies if this skill is executed
from high position.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_11'
old = 'セットボタンを連続して押す'
new = 'Repeatedly press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_14'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_18'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_16'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_19'
old = '敵の攻撃を引きつけてセットボタンを押す'
new = '''
Just as an enemy attacks,
press the assigned button.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_17'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_120'
old = '''
しがみつき中にセットボタンを押した後、
セットボタンを連続して押す'''
new = '''
While climbing an enemy,
press the assigned button,
then repeatedly press the assigned button.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_121'
old = '''
敵の攻撃を引き付けてセットボタンを押す
発動中に再度セットボタンを押すと派生斬り'''
new = '''
Just as an enemy attacks,
press the assigned button.
Press the assigned button again after activation to
invert the direction of the attack.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_154'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_155'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_174'
old = 'セットボタンを連続して押す'
new = 'Repeatedly press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_175'
old = 'セットボタンを連続して押す'
new = 'Repeatedly press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_209'
old = '''
セットボタンを押す
<COL ff7878>威力が最大となる高度からの攻撃で
戦甲へのカウンターに特化</COL> '''
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_210'
old = '''
セットボタンを押す
<COL ff7878>威力が最大となる高度からの攻撃で
戦甲へのカウンターに特化</COL> '''
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_211'
old = 'セットボタンを連続して押す'
new = 'Repeatedly press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_01_212'
old = 'セットボタンを連続して押す'
new = 'Repeatedly press the assigned button.'
