[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_32'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_37'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_33'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_34'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_36'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_38'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_39'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_35'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_42'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_40'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_41'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_43'
old = '''
セットボタンで構え後、<KC SHOOT>で発射
<COL ff7878>溜め満了の瞬間に放つことで
戦甲へのカウンターに特化</COL>'''
# NEEDS REVIEW
new = '''While holding the assigned button, <KC SHOOT> to shoot.
<COL ff7878>Effective against War-Ready enemies if this skill is executed
just as the charge gauge is full.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_131'
old = '''
セットボタンを押す
'''
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_132'
old = 'セットボタンで構え後、セットボタンを連続して押す'
new = '''
After pressing the assigned button,
repeatedly press the assigned button.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_162'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_163'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_164'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_165'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_197'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_198'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_199'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_03_200'
old = 'セットボタンで構え後、<KC SHOOT>で発射'
new = 'While holding the assigned button, <KC SHOOT> to shoot.'
