[[message]]
key = 'CUSTOM_SKILL_INFO_06_68'
old = '''
魔力を溜めた後、
広範囲に向けてブレス状の炎を放つ
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で動作終了間際に追加入力することで
往復攻撃可能</COL>'''
new = '''
After charging magick,
release a breath-like flame in front of you.
<COL ffdc78>LV UP: Increases damage.
LV.6: Press the button right before the end
to repeat the spell.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_72'
old = '''
自身を中心に、一定範囲をカバーする
雷属性の魔法を放つ
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃範囲拡大</COL>'''
new = '''
Emit lightning in a range outwards from you.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_74'
old = '''
魔力を溜めた後、闇の霧を発生させる
霧は敵にまとわりつき、継続ダメージを与える
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で継続時間延長／攻撃ヒット数増加</COL>'''
new = '''
After charging magick, generate a dark fog.
The fog will cling to enemies, dealing damage over time.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases duration of the effect.
Increases the number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_71'
old = '''
魔力を溜めた後、
敵の足元から巨大な氷の塊を出現させる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で術始動時に範囲攻撃追加</COL>'''
new = '''
After charging magick,
generate a giant spire of ice at the enemy's feet.
<COL ffdc78>LV UP: Increases damage.
LV.6: Adds an additional attack at the start
of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_69'
old = '''
魔力を溜めた後、
高い炎の壁を作り出す
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃範囲拡大</COL>'''
new = '''
After charging magick,
generate a towering wall of flame.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_73'
old = '''
魔力を溜めた後、大杖を振りかざして
雷・斬属性を持つ円月状の衝撃波を放つ
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で衝撃波が３方向化</COL>'''
new = '''
After charging magick, brandish your archistaff,
releasing a blade-shaped shockwave.
Inflicts damage with Lightning and Slash attributes.
<COL ffdc78>LV UP: Increases damage.
LV.6: Shockwave will fire in 3 directions.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_75'
old = '''
魔力を溜めた後、地を揺らし岩塊を隆起させ、
闇・打属性によるダメージを与える
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で岩塊数が増加（１→２）</COL>'''
new = '''
After charging magick, shake the earth,
sending eruptions of stone high into the air.
Inflicts damage with Darkness and Impact attributes.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases number of rocks (1→2).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_70'
old = '''
魔力を溜めた後、
敵の頭上に燃え盛る隕石を落下させる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で隕石弾数が増加（４→７）</COL>'''
new = '''
After charging magick, call meteors down from
the heavens to land around the enemy.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases number of meteors (4→7).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_76'
old = '''
魔力を溜めた後、敵の頭上に落雷を発生させる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で落雷数が増加（３→５）</COL>'''
new = '''
After charging magick, smite the enemy
from above with tongues of lightning.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases number of lightning strikes (3→5).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_78'
old = '''
魔力を溜めた後、上空に濃い闇の霧を発生させる
霧に侵入した全ての敵に継続ダメージを与える
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃範囲拡大</COL>'''
new = '''
After charging magick, conjure a dense
dark fog overhead that deals continous
damage to enemies within.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_77'
old = '''
魔力を溜めた後、氷の槍を発現させ前方に放つ
氷・射属性によるダメージを与える
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃範囲拡大</COL>'''
new = '''
After charging magick, conjure a twisting spike
of ice that thrusts forward from the ground.
Inflicts damage with Ice and Shot attributes.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_79'
old = '''
魔力を溜めて凝縮し、無属性の魔球を発現させる
周囲に魔力を解放し大ダメージを与える
爆発範囲は調節可能で、狭いほど高威力
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で爆発範囲の限界幅が拡張</COL>'''
new = '''
After charging magick, conjure a non-elemental
magick orb. The magickal power stored within the orb is released over
a wide area, dealing a great deal of damage to foes within its range.
Especially effective in narrow areas.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Expands the range of the explosion.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_137'
old = '''
魔力を溜めた後、氷の矢を放つ氷塊を発現させ、
任意のタイミングで矢を高速射出する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で矢の数が増加／溜め攻撃が可能</COL>'''
new = '''
After charging magick, conjure a giant snowflake
that calls forth and fires arrows of ice at high velocities.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Increases number of arrows formed and allows the skill
to be charged.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_138'
old = '''
魔力を溜めて雷を引き寄せる魔法杭を発現させ、
自身の杖との間に稲妻を発生させる
<COL ffdc78>LV UP毎にスタミナ消費量の減少
LV.６で攻撃威力上昇／攻撃ヒット数増加</COL>'''
new = '''
Conjure a magickal stake that gathers magickal power from your staff,
and calls down lightning when charged.    
<COL ffdc78>LV UP: Decreases stamina cost of skill.
LV.6: Increases damage of the skill and number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_176'
old = '''
【ＥＸ追加効果】
闇の霧の中心部分のダメージ量が増加
<COL ff7878>亜人／鬼人／巨人の敵に与えるダメージ量が増加</COL>'''
new = '''
EX Additional Effects:
Increase damage to enemies at the center of the mist.
<COL ff7878>Further increase damage to Giant/Ogre/Demihuman enemies.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_177'
old = '''
【ＥＸ追加効果】
毒／睡眠の状態異常を付与'''
new = '''
EX Additional Effects:
Accumulate poison/sleep status effects.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_178'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
攻撃ヒット数が増加'''
new = '''
EX Additional Effects:
Increase damage.
Increase number of hits'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_179'
old = '''
【ＥＸ追加効果】
空中詠唱可能
のけぞり、吹き飛び中でも発動可能'''
new = '''
EX Additional Effects:
Possible to cast in the air or 
when being knocked back.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_221'
old = '''
【ＥＸ追加効果】
中央に巨大な爆炎が追加で発生'''
new = '''
EX Additional Effects:
Create a huge explosion at the center.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_06_222'
old = '''
【ＥＸ追加効果】
攻撃範囲の高度が拡張
延焼エリアに吹き飛ばし力が追加され
展開時間が延長される'''
new = '''
EX Additional Effects:
Increase the altitude range of the attack.
Add blow power to the lingering hits.
Increase duration of the skill.'''