[[message]]
key = 'CUSTOM_SKILL_INFO_07_80'
old = '''
大剣を突き刺し、勢いよく斬り上げる
敵を高く打ち上げることが可能
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６でモーション変化／攻撃ヒット数増加</COL>'''
new = '''
Stabs foes then fiercely slashes upward.
Can send foes flying high into the air.
<COL ffdc78>LV UP: Increases damage.
LV.6: Motion changes. Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_82'
old = '''
大剣の切っ先を前方に構え、
敵を押しこみながら突進する
<PADM>左スティック<KEYM>移動キー</KEYM>で任意方向へ移動できる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で移動距離が延長／攻撃ヒット数増加</COL>'''
new = '''
Charges forward with the blade extended,
knocking down any caught in its path.
Use the <PADM>left stick<KEYM>move key</KEYM> to control the direction.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases movement distance. Increases
number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_81'
old = '''
前方に踏み込みながら剣の柄を打ち込む
敵を怯ませやすく、怒り状態の敵のスタミナも
減らしやすい
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６でスタミナ消費減少／攻撃範囲拡大</COL>'''
new = '''
Lunges in while driving the hilt of the blade into
the target. Though limited in range it easily stuns
foes and reduces the Stamina of enraged enemies.
<COL ffdc78>LV UP: Increases damage.
LV.6: Reduces Stamina cost. Increases range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_83'
old = '''
後方へ避けつつ攻撃を繰り出す
とっさの回避手段としても有効
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６でモーション変化／追加入力で追加攻撃
敵の攻撃を直前回避時、追加攻撃の威力上昇</COL>'''
new = '''
Steps backward in a swift evasive maneuver
while delivering a slashing blow.
<COL ffdc78>LV UP: Increases damage.
LV.6: Motion changes with an additional attack.
Adds an additional input.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_84'
old = '''
素早く大剣を回転させ、
自身の全周囲になぎ払い攻撃を繰り出す
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃範囲拡大</COL>'''
new = '''
Spins the blade in a swift circle,
slashing at foes all around the user.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases the range of the effect.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_85'
old = '''
力を溜め、刀身で敵を叩きつける
敵を気絶させやすい
溜め満了の瞬間にボタンを離すと威力大幅上昇
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で溜め段階拡張（１→２）</COL>'''
new = '''
Build up strength before striking enemies with the side 
of your blade. Has high stunning power. Release the attack
as the charge finishes to increase power significantly.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases total charge stages (1→2).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_87'
old = '''
上空に対して鋭い突きを繰り出す
空中の敵などに有効
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃範囲拡大／攻撃ヒット数増加</COL>'''
new = '''
Thrust your blade with great force into the air.
Especially effective against aerial enemies.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases the range of the effect.
Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_86'
old = '''
大剣を構えて待機、敵の攻撃を弾き返した後、
連続動作で反撃する
敵の攻撃を弾き返したときのみ、連続行動を行う
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加／受付時間延長</COL>'''
new = '''
Hold the blade in wait. Upon deflecting an
enemy's attack, the user will unleash a series of blows.
Only a successful counter will perform multiple blows.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases number of hits. Increases counter duration.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_90'
old = '''
一歩踏み込み、敵の攻撃を受けとめる。様々な動作
から発動することができる（連続では行えない）
攻撃を受けとめるとリベンジゲージが大きく増加
<COL ffdc78>LV UP毎にリベンジゲージ蓄積値上昇
LV.６でのけぞり、吹き飛び中でも発動可能</COL>'''
new = '''
Step inward to receive an enemy's attack.
Can be used out of many different actions. Upon successfully 
receiving an attack, the revenge gauge will fill greatly.
<COL ffdc78>LV UP: Increases revenge gauge accumulation.
LV.6: Can be used even during stagger and knockback.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_89'
old = '''
大剣を左右交互に振り下ろし、連続して敵を斬り刻む
ボタンの連打で攻撃回数が増加する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で最大攻撃回数増加（７→１１）</COL>'''
new = '''
Swing your blade in fierce downward motions left and right,
repeatedly cutting into foes in succession. Continuously
pressing the skill button increases the number of attacks.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases the maximum number of attacks (7→11).</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_91'
old = '''
高く跳躍し、一点集中で力強く大剣を突き立てる
攻撃範囲は狭いが威力は絶大
落下距離により威力が上昇
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加</COL>'''
new = '''
Jump high upward, viciously thrusting the blade at
a concentrated point with great force. The attack's
range is very narrow, but it carries tremendous power.
<COL ffdc78>LV UP: Increases damage.
LV.6: Increases number of hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_88'
old = '''
力を十分に溜めた後、渾身の一撃を繰り出す
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で剣に風圧が追加／攻撃ヒット数増加</COL>'''
new = '''
After channeling enough energy, release
a devastating slash with your body's entire might.
<COL ff7878>Effective against War-Ready enemies.</COL>
<COL ffdc78>LV UP: Increases damage of skill.
LV.6: Adds wind pressure to the blade and increases number of
hits.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_139'
old = '''
しがみついた状態で勢いよく大剣を突き刺し、
体を上下に揺さぶりながら抉る
ボタンの連打で揺さぶり回数が増加する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で最大揺さぶり回数増加</COL>'''
new = '''
While climbing an enemy, thrust the blade
deep into them and vigorously shake it around.
The number of shakes increases with repeated button presses.
<COL ffdc78>LV UP: Increases damage of skill.
LV.6: Increases maximum number of shakes.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_140'
old = '''
渾身の力で大剣を地面に突き刺し、大地を揺るがす
地上ではボタンの長押し、空中では発動時の落下距離
により威力が上昇。倒れた状態の敵に対し真価を発揮
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で溜め段階上昇（１→２）</COL>'''
new = '''
Slam the blade into the ground with the entire
body's might and shake the earth. Performing the skill
from high altitudes while in the air, or holding the
assigned button on the ground increases the damage of the skill.
Especially effective against downed enemies.
<COL ffdc78>LV UP: Increases damage of the skill.
LV.6: Increases maximum charge amount (1→2)</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_180'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
リベンジゲージ最大時に威力が上昇／ヒット数増加
<COL ff7878>亜人／鬼人／巨人系の敵に与えるダメージ量が増加</COL>'''
new = '''
EX Additional Effects:
Increase damage.
Further increase damage when revenge gauge is full.
<COL ff7878>Further increase damage to Demihuman/Ogre/Giant enemies.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_181'
old = '''
【ＥＸ追加効果】
攻撃を受ける瞬間に発動すると
ダメージ量が増加すると同時に
攻撃を敵に接触させる度にリベンジゲージが増加'''
new = '''
EX Additional Effects:
If this skill is used before being hit, damage increases and
revenge gauge increases as you hit enemies.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_182'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
気絶攻力が増加
攻撃回数が増加（１→２）
２回目の攻撃はボタン長押しで溜め可能'''
new = '''
EX Additional Effects:
Increase damage.
Increase knockout power.
Increase the number of hits (1→2)
The second hit can be activated by pressing
and holding the assigned button.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_183'
old = '''
【ＥＸ追加効果】
チャンス攻力がやや増加
疲労攻力がやや増加
<COL ff7878>戦甲を攻撃時、ダメージ量が増加</COL>'''
new = '''
EX Additional Effects:
Slightly increase chance attack.
Slightly increase exhaust power.
<COL ff7878>Further increase damage against War-Ready enemies</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_225'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
リベンジゲージ最大時に威力が上昇
敵の攻撃を直前回避すると追加攻撃のすり抜け時間が延長'''
new = '''
EX Additional Effects:
Increase damage.
Further increase damage when revenge gauge is full.
Increase invulnerability duration if you avoid the enemy at the
closest possible moment.'''
[[message]]
key = 'CUSTOM_SKILL_INFO_07_226'
old = '''
【ＥＸ追加効果】
敵の攻撃を直前回避すると
追加攻撃のダメージ量が増加すると同時に
攻撃を敵に接触させる度にリベンジゲージが増加'''
new = '''
EX Additional Effects:
Increase damage of the additional hits after evasion
if you avoid the enemy at the closest possible moment.
Increase revenge gauge as you hit enemies.'''