[[message]]
key = 'CUSTOM_SKILL_NAME_11_237'
old = '光円月'
new = 'Full Moon Light'
[[message]]
key = 'CUSTOM_SKILL_NAME_11_241'
old = 'ミラージュ・シフト'
new = 'Mirage Shift'
[[message]]
key = 'CUSTOM_SKILL_NAME_11_244'
old = 'ディム・スライス'
new = 'Dim Slice'
[[message]]
key = 'CUSTOM_SKILL_NAME_11_240'
old = '黒閃牙'
new = 'Black Flash Fang'
[[message]]
key = 'CUSTOM_SKILL_NAME_11_238'
old = 'ウォール・バリア'
new = 'Wall Barrier'
[[message]]
key = 'CUSTOM_SKILL_NAME_11_242'
old = 'テラー・ブラスト'
new = 'Terror Blast'
[[message]]
key = 'CUSTOM_SKILL_NAME_11_239'
old = 'エクリプス・ブライト'
new = 'Eclipse Bright'
