[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_143'
old = '''
セットボタンを押す
LV.６で再度セットボタンを押すと派生斬り
アタックブーストで強化可能'''
new = '''
Press the assigned button.
At LV.6, press the assigned button again to
invert slash direction.
Further enhanced with Attack Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_144'
old = '''
セットボタンを押す
アタックブーストで強化可能'''
new = '''
Press the assigned button.
Further enhanced with Attack Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_146'
old = '''
セットボタンを押す
アタックブーストで強化可能'''
new = '''
Press the assigned button.
Further enhanced with Attack Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_149'
old = '''
セットボタンを押す
ヒールブーストで強化可能'''
new = '''
Press the assigned button.
Further enhanced with Heal Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_145'
old = '''
セットボタンを連続して押す
アタックブーストで強化可能'''
new = '''
Repeatedly press the assigned button.
Further enhanced with Attack Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_147'
old = '''
セットボタンを押す
発現後、再度セットボタンを押すと起爆
アタックブーストで強化可能'''
new = '''
Press the assigned button.
After conjuring, press the assigned button
again to detonate.
Further enhanced with Attack Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_150'
old = '''
セットボタンを押す
展開後、その場に留まることで展開時間を延長
ヒールブーストで強化可能'''
new = '''
Press the assigned button.
After deployment, extend duration by
staying in place.
Further enhanced with Heal Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_148'
old = '''
セットボタンを押す
発現後、再度セットボタンを押すと攻撃
アタックブーストで強化可能 
<COL ff7878>バリアの霊力最大時の発動で戦甲へのカウンターに特化</COL>'''
# NEEDS REVIEW
new = '''
Press the assigned button.
After forming the barrier, press the assigned button
to release energy. Further enhanced with Attack Boost.
<COL ff7878>Effective against War-Ready enemies if this skill is executed
at maximum spiritual accumulation.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_153'
old = '''
セットボタンを押す
アタックブーストで強化可能'''
new = '''
Press the assigned button.
Further enhanced with Attack Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_188'
old = '''
セットボタンを押す
ヒールブーストで強化可能'''
new = '''
Press the assigned button.
Further enhanced with Heal Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_195'
old = '''
セットボタンを押す
ヒールブーストで強化可能'''
new = '''
Press the assigned button.
Further enhanced with Heal Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_196'
old = '''
セットボタンを押す
ヒールブーストで強化可能'''
new = '''
Press the assigned button.
Further enhanced with Heal Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_193'
old = '''
セットボタンを押す
再度セットボタンを押すと派生斬り
アタックブーストで強化可能'''
new = '''
Press the assigned button.
Press the assigned button again to invert slash direction.
Further enhanced with Attack Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_194'
old = '''
セットボタンを押す
再度セットボタンを押すと派生斬り
アタックブーストで強化可能'''
new = '''
Press the assigned button.
Press the assigned button again to invert slash direction.
Further enhanced with Attack Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_233'
old = '''
セットボタンを押す
アタックブーストで強化可能'''
new = '''
Press the assigned button.
Further enhanced with Attack Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_234'
old = '''
セットボタンを押す
アタックブーストで強化可能'''
new = '''
Press the assigned button.
Further enhanced with Attack Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_235'
old = '''
セットボタンを押す
展開後、その場に留まることで展開時間を延長
ヒールブーストで強化可能'''
new = '''
Press the assigned button.
After deployment, extend duration by
staying in place.
Further enhanced with Heal Boost.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_236'
old = '''
セットボタンを押す
展開後、その場に留まることで展開時間を延長
ヒールブーストで強化可能'''
new = '''
Press the assigned button.
After deployment, extend duration by
staying in place.
Further enhanced with Heal Boost.'''
