[[message]]
key = 'CUSTOM_SKILL_NAME_07_80'
old = '突き上げ斬り'
new = 'Upward Strike'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_82'
old = '魔人駆け'
new = 'Savage Lunge'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_81'
old = '柄打ち'
new = 'Pommel Strike'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_83'
old = 'かわし斬り'
new = 'Escape Slash'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_84'
old = '大輪斬'
new = 'Spark Slash'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_85'
old = '魔人崩し'
new = 'Devil Burst'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_87'
old = '天衝刃'
new = 'Heaven Thrust'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_86'
old = '無心斬'
new = 'Clarity'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_90'
old = '凌魔の身構え'
new = 'Defensive Stance'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_89'
old = '大風車斬り'
new = 'Great Windmill'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_91'
old = '飛龍突'
new = 'Flying Dragon Crash'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_88'
old = '殲魔剣風斬'
new = "Annihilator's Wind Slash"
[[message]]
key = 'CUSTOM_SKILL_NAME_07_139'
old = '大牙抉り'
new = 'Great Gouging Fang'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_140'
old = '地衝牙'
new = 'Earthquake Fang'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_180'
old = '魔人駆け 剛'
new = 'Savage Lunge (P)'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_181'
old = '魔人駆け 技'
new = 'Savage Lunge (T)'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_182'
old = '柄打ち 剛'
new = 'Pommel Strike (P)'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_183'
old = '柄打ち 技'
new = 'Pommel Strike (T)'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_225'
old = 'かわし斬り 剛'
new = 'Escape Slash (P)'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_226'
old = 'かわし斬り 技'
new = 'Escape Slash (T)'
