[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_105'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_104'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_108'
old = '''
<PADM>セットボタンを押し、左スティックを倒して５属性を選択<KEYM>セットボタンを押し、マウス移動で５属性を選択</KEYM>
<KC ATTACK1>または<KC ATTACK2>を押して属性決定'''
new = '''
Press <PADM>the assigned button<KEYM>the assigned button</KEYM>, then select from <PADM>5<KEYM>5</KEYM>
elements using <PADM>the left stick<KEYM>mouse movement</KEYM>.
Press <KC ATTACK1> or <KC ATTACK2> to confirm element choice.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_109'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_107'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_106'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_110'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_111'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_112'
old = '''
セットボタンを押す
<COL ff7878>錬成値が最大の状態での発動で
戦甲へのカウンターに特化</COL>'''
# NEEDS REVIEW
new = '''Press the assigned button.
<COL ff7878>Effective against War-Ready enemies if this skill is executed
on a full elixir stack.</COL>'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_113'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_114'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_115'
old = '''
セットボタンを連続して押す
展開後、その場に留まることで展開時間を延長'''
new = '''
Repeatedly press the assigned button.
After deployment, extend duration by
staying in place.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_189'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_190'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_191'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_192'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_229'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_230'
old = 'セットボタンを押す'
new = 'Press the assigned button.'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_231'
old = '''
<PADM>セットボタンを押し、左スティックを倒して５属性を選択<KEYM>セットボタンを押し、マウス移動で５属性を選択</KEYM>
<KC ATTACK1>または<KC ATTACK2>を押して属性決定'''
new = '''
Press <PADM>the assigned button<KEYM>the assigned button</KEYM>, then select from <PADM>5<KEYM>5</KEYM>
elements using <PADM>the left stick<KEYM>mouse movement</KEYM>.
Press <KC ATTACK1> or <KC ATTACK2> to confirm element choice.'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_09_232'
old = '''
<PADM>セットボタンを押し、左スティックを倒して５属性を選択<KEYM>セットボタンを押し、マウス移動で５属性を選択</KEYM>
<KC ATTACK1>または<KC ATTACK2>を押して属性決定'''
new = '''
Press <PADM>the assigned button<KEYM>the assigned button</KEYM>, then select from <PADM>5<KEYM>5</KEYM>
elements using <PADM>the left stick<KEYM>mouse movement</KEYM>.
Press <KC ATTACK1> or <KC ATTACK2> to confirm element choice.'''
