[[message]]
key = 'CUSTOM_SKILL_NAME_10_143'
old = 'アラム・ファング'
new = 'Aurom Fang'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_144'
old = 'アラム・スレイ'
new = 'Aurom Slay'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_146'
old = 'コル・スパイク'
new = 'Corr Spike'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_149'
old = 'ウォール・グラスタ'
new = 'Wall Glasta'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_145'
old = 'コル・ストルム'
new = 'Corr Storm'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_147'
old = 'シュクリス・ブラスト'
new = 'Shukris Blast'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_150'
old = 'キュア・グラスタ'
new = 'Cure Glasta'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_148'
old = 'シュクリス・ガーダー'
new = 'Scrios Guard'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_153'
old = 'コル・ミーティア'
new = 'Corr Meteor'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_188'
old = 'エードラム・カウンター'
new = 'Éadrom Counter'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_195'
old = 'ウォール・グラスタ 剛'
new = 'Wall Glasta (P)'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_196'
old = 'ウォール・グラスタ 技'
new = 'Wall Glasta (T)'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_193'
old = 'アラム・ファング 剛'
new = 'Aurom Fang (P)'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_194'
old = 'アラム・ファング 技'
new = 'Aurom Fang (T)'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_233'
old = 'コル・スパイク 剛'
new = 'Corr Spike (P)'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_234'
old = 'コル・スパイク 技'
new = 'Corr Spike (T)'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_235'
old = 'キュア・グラスタ 剛'
new = 'Cure Glasta (P)'
[[message]]
key = 'CUSTOM_SKILL_NAME_10_236'
old = 'キュア・グラスタ 技'
new = 'Cure Glasta (T)'
