[[message]]
key = 'NORMAL_SKILL_NAME_10_149'
old = 'スラスト'
new = 'Thrust'
[[message]]
key = 'NORMAL_SKILL_NAME_10_150'
old = 'スラスト・モール'
new = 'Thrust More'
[[message]]
key = 'NORMAL_SKILL_NAME_10_158'
old = 'フォル・スラスト'
new = 'Fall Thrust'
[[message]]
key = 'NORMAL_SKILL_NAME_10_159'
old = 'エア・スラスト'
new = 'Air Thrust'
[[message]]
key = 'NORMAL_SKILL_NAME_10_151'
old = 'エイド'
new = 'Aid'
[[message]]
key = 'NORMAL_SKILL_NAME_10_152'
old = 'エイド・モール'
new = 'Aid Mór'
[[message]]
key = 'NORMAL_SKILL_NAME_10_161'
old = 'フォル・ムーヴ'
new = 'Fall Move'
[[message]]
key = 'NORMAL_SKILL_NAME_10_153'
old = 'スカー・ムーヴ'
new = 'Scáth Move'
[[message]]
key = 'NORMAL_SKILL_NAME_10_155'
old = 'アタックブースト'
new = 'Attack Boost'
[[message]]
key = 'NORMAL_SKILL_NAME_10_156'
old = 'ヒールブースト'
new = 'Heal Boost'
[[message]]
key = 'NORMAL_SKILL_NAME_10_162'
old = 'ブースト解除'
new = 'Boost Cancel'
[[message]]
key = 'NORMAL_SKILL_NAME_10_160'
old = 'イラー・スラスト'
new = 'Iolar Thrust'
[[message]]
key = 'NORMAL_SKILL_NAME_10_163'
old = 'ブースト解除'
new = 'Boost Cancel'
