[[message]]
key = 'DRAGON_SKILL_NAME_1'
old = '竜の加護'
new = 'Dragon Protection'
[[message]]
key = 'DRAGON_SKILL_NAME_2'
old = 'ビーストスレイヤー'
new = 'Beast Slayer'
[[message]]
key = 'DRAGON_SKILL_NAME_3'
old = 'デーモンスレイヤー'
new = 'Demon Slayer'
[[message]]
key = 'DRAGON_SKILL_NAME_4'
old = 'ゴーストスレイヤー'
new = 'Spirit Slayer'
[[message]]
key = 'DRAGON_SKILL_NAME_5'
old = 'ドラゴンスレイヤー'
new = 'Dragon Slayer'
[[message]]
key = 'DRAGON_SKILL_NAME_6'
old = '精霊竜の抱擁'
new = 'Embrace of the Spirit Dragon'
[[message]]
key = 'DRAGON_SKILL_NAME_7'
old = '精霊竜の反撃'
new = 'Counterattack of the Spirit Dragon'
[[message]]
key = 'DRAGON_SKILL_NAME_8'
old = '火竜の浄化'
new = 'Purification of the Fire Dragon'
[[message]]
key = 'DRAGON_SKILL_NAME_9'
old = '火竜の魔防壁'
new = 'Demon Bulwark of the Fire Dragon'
[[message]]
key = 'DRAGON_SKILL_NAME_10'
old = '白竜の防壁'
new = 'Bulwark of the White Dragon'
[[message]]
key = 'DRAGON_SKILL_NAME_11'
old = '白竜の刃'
new = 'Edge of the White Dragon'
[[message]]
key = 'DRAGON_SKILL_NAME_12'
old = '竜の祝福'
new = 'Dragon Blessing'
[[message]]
key = 'DRAGON_SKILL_NAME_13'
old = '黄金竜の一撃'
new = 'Blow of the Golden Dragon'
