[[message]]
key = 'bbi_match_msg_001'
old = '現在のパーティーメンバーのジョブ構成／進行状況'
new = 'Job Composition/Progress of Current Party Members'
[[message]]
key = 'bbi_match_msg_002'
old = '名前'
new = 'Name'
[[message]]
key = 'bbi_match_msg_003'
old = 'ジョブレベル'
new = 'Job Level'
[[message]]
key = 'bbi_match_msg_004'
old = '進行状況'
new = 'Progress'
[[message]]
key = 'bbi_match_msg_005'
old = '突入'
new = 'Embark'
[[message]]
key = 'bbi_match_msg_006'
old = '進行状況が合わないメンバーがいるため、突入できません'
new = 'Cannot enter because there are members with different progress.'
[[message]]
key = 'bbi_match_msg_007'
old = 'リーダーが突入を開始していないため、突入できません'
new = 'Cannot enter because leader has not started.'
[[message]]
key = 'bbi_match_msg_008'
old = 'クイックパーティー'
new = 'Quick Party'
[[message]]
key = 'bbi_match_msg_009'
old = '進行状況が合わないメンバーがいるため、クイックパーティーできません'
new = 'Cannot use quick party because there are members with different progress.'
[[message]]
key = 'bbi_match_msg_010'
old = 'パーティーメンバーが揃っているため選べません'
new = 'Cannot select this option because your party is full.'
[[message]]
key = 'bbi_match_msg_011'
old = '所在状況'
new = 'Status'
[[message]]
key = 'bbi_match_msg_012'
old = '所在状況が合わないメンバーがいるため、突入できません'
new = 'Cannot enter because there are members in different location.'
[[message]]
key = 'bbi_match_msg_013'
old = '所在状況が合わないメンバーがいるため、クイックパーティーできません'
new = 'Cannot use quick party because there are members in different location.'