[[message]]
key = 'common_next'
old = '次へ'
new = 'Next'
[[message]]
key = 'common_yes'
old = 'はい'
new = 'Yes'
[[message]]
key = 'common_no'
old = 'いいえ'
new = 'No'
[[message]]
key = 'common_decide'
old = '決定'
new = 'OK'
[[message]]
key = 'common_cancel'
old = 'キャンセル'
new = 'Cancel'
[[message]]
key = 'common_back'
old = '戻る'
new = 'Back'
[[message]]
key = 'common_end'
old = '終了'
new = 'End'
[[message]]
key = 'common_serch'
old = '検索'
new = 'Search'
[[message]]
key = 'common_entry'
old = '登録'
new = 'Register'
[[message]]
key = 'common_ok'
old = 'OK'
new = 'OK'
[[message]]
key = 'common_unit_g'
old = 'G'
new = 'G'
[[message]]
key = 'common_unit_r'
old = 'R'
new = 'R'
[[message]]
key = 'common_unit_bo'
old = 'BO'
new = 'BO'
[[message]]
key = 'common_unit_gp'
old = 'GP'
new = 'GP'
[[message]]
key = 'common_unit_xp'
old = 'XP'
new = 'XP'
[[message]]
key = 'common_unit_jp'
old = 'JP'
new = 'JP'
[[message]]
key = 'common_unit_cap'
old = 'CAP'
new = 'CAP'
[[message]]
key = 'common_unit_ap'
old = 'AP'
new = 'AP'
[[message]]
key = 'common_unit_pt'
old = 'pt'
new = 'pt'
[[message]]
key = 'common_unit_cp'
old = 'CP'
new = 'CP'
[[message]]
key = 'common_unit_cr'
old = 'CR'
new = 'CR'
[[message]]
key = 'common_unit_lv'
old = 'LV.'
new = 'LV.'
[[message]]
key = 'common_unitname_g'
old = 'ゴールド'
new = 'Gold'
[[message]]
key = 'common_unitname_r'
old = 'リム'
new = 'Rift Crystal'
[[message]]
key = 'common_unitname_bo'
old = 'ブラッドオーブ'
new = 'Blood Orb'
[[message]]
key = 'common_unitname_jp'
old = 'ジョブポイント'
new = 'Job Point'
[[message]]
key = 'common_edit'
old = '編集'
new = 'Edit'
[[message]]
key = 'common_clan_s_begin'
old = '≪'
new = '≪'
[[message]]
key = 'common_clan_s_end'
old = '≫'
new = '≫'
[[message]]
key = 'common_unitname_gs'
old = '黄金石'
new = 'Golden Gemstone'
[[message]]
key = 'common_name'
old = '名前'
new = 'Name'
[[message]]
key = 'common_level'
old = 'レベル'
new = 'Level'
[[message]]
key = 'common_mymsg'
old = 'マイ定型文セット'
new = 'My Phrase '
[[message]]
key = 'common_above'
old = '～'
new = '～'
[[message]]
key = 'common_open_bracket'
old = '('
new = '('
[[message]]
key = 'common_close_bracket'
old = ')'
new = ')'
[[message]]
key = 'common_grade'
old = '★'
new = '★'
[[message]]
key = 'common_up'
old = 'UP'
new = 'UP'
[[message]]
key = 'common_down'
old = 'DOWN'
new = 'DOWN'
[[message]]
key = 'common_off'
old = 'OFF'
new = 'OFF'
[[message]]
key = 'common_max'
old = 'MAX'
new = 'MAX'
[[message]]
key = 'common_hyphen'
old = '-'
new = '-'
[[message]]
key = 'common_plus'
old = '+'
new = '+'
[[message]]
key = 'common_complete'
old = '完了'
new = 'Complete'
[[message]]
key = 'common_select_clan_motto'
old = 'モットーを１つ以上選択してください'
new = 'Please select one or more mottos'
[[message]]
key = 'common_select_clan_day'
old = '活動時間帯を選択してください'
[[message]]
key = 'common_select_clan_hour'
old = '活動時間帯を選択してください'
[[message]]
key = 'common_select_clan_feature'
old = '特徴を１つ以上選択してください'
[[message]]
key = 'common_guide_blank'
old = ''
new = ''
[[message]]
key = 'common_guide_change_info'
old = '情報切り替え'
new = 'Change Info'
[[message]]
key = 'common_guide_close'
old = '閉じる'
new = 'Close'
[[message]]
key = 'common_guide_submenu'
old = 'サブメニュー'
new = 'Submenu'
[[message]]
key = 'common_guide_decide'
old = '決定'
new = 'OK'
[[message]]
key = 'common_guide_execute'
old = '実行'
new = 'Execute'
[[message]]
key = 'common_guide_end'
old = '終了'
new = 'Exit'
[[message]]
key = 'common_guide_change_page'
old = 'ページ切り替え'
new = 'Change Page'
[[message]]
key = 'common_guide_return'
old = '戻る'
new = 'Back'
[[message]]
key = 'common_date_format'
old = '%Y/%m/%d'
new = '%Y/%m/%d'
[[message]]
key = 'common_guide_open'
old = '開く'
new = 'Open'
[[message]]
key = 'common_delete'
old = '削除'
new = 'Delete'
[[message]]
key = 'common_rest_time'
old = '時間'
new = 'h'
[[message]]
key = 'common_rest_day'
old = '日'
new = 'd'
[[message]]
key = 'common_unit_gs'
old = '個'
new = 'x'
[[message]]
key = 'common_indicator_lestania'
old = 'GT'
new = 'GT'
[[message]]
key = 'common_indicator_local'
old = 'LT'
new = 'LT'
[[message]]
key = 'common_indicator_server'
old = 'ST'
new = 'ST'
[[message]]
key = 'common_indicator_lobby'
old = 'World'
new = 'World'
[[message]]
key = 'common_key_alt'
old = 'Alt'
new = 'Alt'
[[message]]
key = 'common_indicator_saving'
old = 'セーブ中'
new = 'Saving'
[[message]]
key = 'common_guide_replacement'
old = '入れ替え'
new = 'Replace'
[[message]]
key = 'common_guide_set'
old = 'セット'
new = 'Set'
[[message]]
key = 'common_guide_drag'
old = 'つかむ'
new = 'Drag'
[[message]]
key = 'common_guide_goto_itembag'
old = 'アイテムバッグに移動'
new = 'Go to Item Bag'
[[message]]
key = 'common_rest_minute'
old = '分'
new = 'm'
[[message]]
key = 'common_time_limit'
old = 'あと'
new = 'Left: '
[[message]]
key = 'common_time_after'
old = '後'
new = 'After'
[[message]]
key = 'common_time_before'
old = '前'
new = ' ago'
[[message]]
key = 'common_unit_turn'
old = '回'
new = 'Time'
[[message]]
key = 'common_unit_body'
old = '体'
new = 'x'
[[message]]
key = 'common_switch_expand'
old = '拡張枠'
new = 'Expansion'
[[message]]
key = 'common_switch_strage'
old = '通常枠'
new = 'Normal'
[[message]]
key = 'common_numbox'
old = '直接入力'
new = 'Direct Input'
[[message]]
key = 'common_switch_storagebox'
old = '保管ボックス'
new = 'Storage Box'
[[message]]
key = 'common_switch_itembag'
old = 'アイテムバッグ'
new = 'Item Bag'
[[message]]
key = 'common_guide_shortcut_set'
old = 'ショートカット登録'
new = 'Register Shortcut'
[[message]]
key = 'common_system_savedata'
old = 'システムセーブデータ'
new = 'System Save Data'
[[message]]
key = 'common_edit_savedata'
old = 'エディットデータ'
new = 'Edit Data'
[[message]]
key = 'common_new_edit_savedata'
old = '新しいエディットデータ'
[[message]]
key = 'common_edit_savedata_author'
old = '作成者：'
new = 'Author: '
[[message]]
key = 'common_edit_savedata_sex'
old = '性別：'
new = 'Gender: '
[[message]]
key = 'common_edit_savedata_comment'
old = 'コメント：'
new = 'Comment: '
[[message]]
key = 'common_chat_ch_general'
old = 'General'
[[message]]
key = 'common_chat_ch_party'
old = 'Party'
[[message]]
key = 'common_unitname_silverticket'
old = 'シルバーチケット'
new = 'Silver Ticket'
[[message]]
key = 'common_titlename_jp'
old = 'ドラゴンズドグマ オンライン'
new = "Dragon's Dogma Online"
[[message]]
key = 'common_clan_search_on'
old = 'クラン情報公開'
new = 'Clan info public'
[[message]]
key = 'common_clan_search_off'
old = 'クラン情報非公開'
new = 'Clan info private'
[[message]]
key = 'common_select_clan_motto_search'
old = 'モットーを２つまで選択してください'
[[message]]
key = 'common_select_clan_day_search'
old = '活動時間帯を選択してください'
[[message]]
key = 'common_select_clan_hour_search'
old = '活動時間帯を選択してください'
[[message]]
key = 'common_select_clan_feature_search'
old = '特徴を４つまで選択してください'
[[message]]
key = 'common_unitname_rp'
old = 'レンタルポイント'
new = 'Rental Point'
[[message]]
key = 'common_unit_rp'
old = 'RP'
new = 'RP'
[[message]]
key = 'common_guide_drag_mousedrag'
old = 'つかむ(ドラッグ操作)'
new = 'Drag'
[[message]]
key = 'common_percent'
old = '%'
new = '%'
[[message]]
key = 'common_enemy_transform_erosion_01'
old = '・軽度'
new = ' (Slight)'
[[message]]
key = 'common_enemy_transform_erosion_02'
old = '・重度'
new = ' (Severe)'
[[message]]
key = 'common_enemy_transform_erosion_03'
old = '・危険'
new = ' (Critical)'
[[message]]
key = 'common_switch_deposit'
old = '通常枠'
new = 'Normal'
[[message]]
key = 'common_unit_multiplication'
old = '×'
new = '×'
[[message]]
key = 'common_quest_unpublished'
old = '？？？？？？'
new = '??????'
[[message]]
key = 'common_custom_skill_pallet_sub'
old = 'パレット サブ'
new = 'Sub Palette'
[[message]]
key = 'common_custom_skill_pallet_main'
old = 'パレット メイン'
new = 'Main Palette'
[[message]]
key = 'common_equip_ir'
old = 'IR.'
[[message]]
key = 'common_unitname_craftskillreset'
old = 'クラフトスキルリセット'
new = 'Reset Craft Skills'
[[message]]
key = 'common_switch_deposit_ex01'
old = '拡張枠'
new = 'Expansion'
[[message]]
key = 'common_colon'
old = '：'
new = ': '
[[message]]
key = 'common_nakaten'
old = '・'
new = '・'
[[message]]
key = 'common_unit_pp'
old = 'PP'
new = 'PP'
[[message]]
key = 'common_next_en'
old = 'Next'
new = 'Next'
[[message]]
key = 'common_date'
old = '日付'
new = 'Date'
[[message]]
key = 'common_unitname_cp'
old = 'クランポイント'
new = 'Clan Point'
[[message]]
key = 'common_enemy'
old = '魔物'
new = 'Enemy'
[[message]]
key = 'common_enemy_transform_erosion_04'
old = '・崩化'
new = ' (Ruin)'
[[message]]
key = 'common_question'
old = '?'
new = '?'
[[message]]
key = 'common_inequality_left'
old = '＜'
new = '<'
[[message]]
key = 'common_inequality_right'
old = '＞'
new = '>'
[[message]]
key = 'common_unit_dp'
old = 'DP'
new = 'DP'
[[message]]
key = 'common_unit_hb'
old = 'HO'
new = 'HO'
[[message]]
key = 'common_none_nasi'
old = 'なし'
new = 'None'
[[message]]
key = 'common_unitname_hb'
old = 'ハイオーブ'
new = 'High Orb'
[[message]]
key = 'common_partyboard_type01'
old = 'パーティー募集掲示板'
new = 'Party Recruitment Board'
[[message]]
key = 'common_unit_tp'
old = 'BP'
new = 'BP'
[[message]]
key = 'common_unit_ep'
old = 'EP'
new = 'EP'
[[message]]
key = 'common_equal'
old = '='
new = '='
[[message]]
key = 'common_percent_big'
old = '％'
new = '％'
[[message]]
key = 'common_plus_big'
old = '＋'
new = '＋'
[[message]]
key = 'common_hyphen_big'
old = '－'
new = '－'
[[message]]
key = 'common_enemy_transform_armed_01'
old = '・軽装'
new = ' (Light Armor)'
[[message]]
key = 'common_enemy_transform_armed_02'
old = '・重装'
new = ' (Heavy Armor)'
[[message]]
key = 'common_enemy_transform_armed_03'
old = '・神装'
new = ' (Supreme Armor)'
[[message]]
key = 'common_unitname_tp'
old = '冒パスポイント'
new = 'Adventure Pass Point'
[[message]]
key = 'common_unitname_dp'
old = 'ドミニオンポイント'
new = 'Dominion Point'
[[message]]
key = 'common_unit_ptp'
old = '育成EXP'
new = 'Training EXP'
[[message]]
key = 'common_unit_pap'
old = '対話回数'
new = 'Dialogue Count'
[[message]]
key = 'common_slash'
old = '/'
new = '/'
[[message]]
key = 'common_unit_silverticket'
old = '枚'
new = 'x'
[[message]]
key = 'common_unitname_evoticket'
old = 'カスタムメイドサービス券'
new = 'Custom-Made Service Ticket'
[[message]]
key = 'common_unit_evoticket'
old = '枚'
new = 'x'
[[message]]
key = 'common_possession'
old = '獲得'
[[message]]
key = 'common_double'
old = '倍'
[[message]]
key = 'common_jp_kuten'
old = '。'
new = '.'
[[message]]
key = 'common_jp_touten'
old = '、'
new = ', '
[[message]]
key = 'common_msg_details'
old = 'Details'
[[message]]
key = 'common_unitname_dragon_mark_01'
old = '金竜の印'
new = 'Gold Dragon Mark'
[[message]]
key = 'common_unitname_dragon_mark_02'
old = '銀竜の印'
new = 'Silver Dragon Mark'
[[message]]
key = 'common_unitname_dragon_mark_03'
old = '赤竜の印'
new = 'Red Dragon Mark'
[[message]]
key = 'common_unitname_entrance_right'
old = '黒呪の迷宮リセット券'
new = 'Bitterblack Maze Reset Ticket'
[[message]]
key = 'common_open_onlineshop'
old = 'オンラインショップを開く'
new = 'Open Online Shop'
[[message]]
key = 'common_msg_gs_lack'
old = '''
黄金石が不足しています
（所持数：<VAL>）'''
[[message]]
key = 'common_msg_state_progress'
old = '進行状況'
new = 'Status'
[[message]]
key = 'common_msg_reward'
old = '探索'
new = 'Reward'
[[message]]
key = 'common_msg_received'
old = 'クリア報酬が発生しません'
new = 'Clear Reward Unavailable'
[[message]]
key = 'common_msg_not_received'
old = '階層ごとの報酬が入手可能'
new = 'Level Reward Available'
[[message]]
key = 'common_msg_visit_on'
old = '訪問を許可する'
new = 'Visit Allowed'
[[message]]
key = 'common_msg_visit_off'
old = '訪問を許可しない'
new = 'Visit Denied'
[[message]]
key = 'common_msg_pawnthink_totalnum'
old = '育成LV'
new = 'Training LV'
[[message]]
key = 'common_language_ng'
old = 'NG'
new = 'NG'
[[message]]
key = 'common_draskill_1'
old = '理力'
new = 'Force'
[[message]]
key = 'common_draskill_2'
old = '精霊竜'
new = 'Spirit Dragon'
[[message]]
key = 'common_draskill_3'
old = '火竜'
new = 'Fire Dragon'
[[message]]
key = 'common_draskill_4'
old = '白竜'
new = 'White Dragon'
[[message]]
key = 'common_draskill_5'
old = '黄金竜'
new = 'Golden Dragon'
[[message]]
key = 'common_entry_pawn_no_adv'
old = '冒険回数0'
[[message]]
key = 'common_msg_jp_of'
old = 'の'
new = "'s "
[[message]]
key = 'common_msg_attribute_A1'
old = '斬'
new = 'Slash'
[[message]]
key = 'common_msg_attribute_A2'
old = '打'
new = 'Impact'
[[message]]
key = 'common_msg_attribute_A3'
old = '射'
new = 'Pierce'
[[message]]
key = 'common_msg_attribute_B1'
old = '無'
new = 'Null'
[[message]]
key = 'common_msg_attribute_B2'
old = '炎'
new = 'Fire'
[[message]]
key = 'common_msg_attribute_B3'
old = '氷'
new = 'Ice'
[[message]]
key = 'common_msg_attribute_B4'
old = '雷'
new = 'Thunder'
[[message]]
key = 'common_msg_attribute_B5'
old = '聖'
new = 'Holy'
[[message]]
key = 'common_msg_attribute_B6'
old = '闇'
new = 'Dark'
[[message]]
key = 'common_msg_jp_attribute'
old = '属性'
new = ' Attribute'
[[message]]
key = 'common_msg_jp_damage'
old = 'ダメージ'
new = ' Damage'
[[message]]
key = 'common_msg_en_parameter'
old = 'Parameter'
[[message]]
key = 'common_msg_en_dragonskills'
old = 'Dragon Ability Points'
[[message]]
key = 'common_draskill_6'
old = '対黒竜'
new = 'Anti-Black Dragon'
[[message]]
key = 'common_msg_jp_dragonskills'
old = 'ドラゴンアビリティ'
new = 'Dragon Ability'
[[message]]
key = 'common_msg_not_received_EX'
old = '階層ごとの報酬が入手可能<COL ffdc78>（報酬UP）</COL>'
[[message]]
key = 'common_on'
old = 'ON'
new = 'ON'
[[message]]
key = 'common_msg_jp_assignment'
old = '指定'
[[message]]
key = 'common_enemy_transform_division_01'
old = '・分身体'
new = ' (Avatar)'
[[message]]
key = 'common_enemy_transform_division_02'
old = '・分身体Ⅰ'
new = ' (Avatar 1)'
[[message]]
key = 'common_enemy_transform_division_03'
old = '・分身体Ⅱ'
new = ' (Avatar 2)'
