[[message]]
key = 'entry_board_title_jp'
old = 'エントリーボード'
new = 'Entry Board'
[[message]]
key = 'entry_board_title_en'
old = 'Entry Board'
new = 'Entry Board'
[[message]]
key = 'entry_board_comment'
old = 'コメント'
new = 'Comment'
[[message]]
key = 'entry_board_leader'
old = '募集主'
new = 'Leader'
[[message]]
key = 'entry_board_entry'
old = '参加人数'
new = 'Participants'
[[message]]
key = 'entry_board_recruit'
old = '新規募集'
new = 'Recruit Members'
[[message]]
key = 'entry_board_search'
old = '検索'
new = 'Search'
[[message]]
key = 'entry_board_param1'
old = '<VAL> <VAL>'
new = '<VAL> <VAL>'
[[message]]
key = 'entry_board_param2'
old = '<VAL>/<VAL>'
new = '<VAL>/<VAL>'
[[message]]
key = 'entry_board_search_search_job'
old = 'ジョブを指定して探す'
new = 'Search Jobs Allowed'
[[message]]
key = 'entry_board_search_search'
old = '検索条件の設定'
new = 'Set Search Conditions'
[[message]]
key = 'entry_board_search_search_friend_friend'
old = '知り合いが参加しているエントリーで探す'
new = 'Look for entries where friends are participating'
[[message]]
key = 'entry_board_search_search_name'
old = '名前を指定して探す'
new = 'Search by Name'
[[message]]
key = 'entry_board_search_search_friend'
old = 'フレンド'
new = 'Friends'
[[message]]
key = 'entry_board_search_search_password'
old = 'パスワード設定なし'
new = 'No Password Set'
[[message]]
key = 'entry_board_search_search_clanmember'
old = 'クラン'
new = 'Clan Members'
[[message]]
key = 'entry_board_search_all'
old = '全て'
new = 'All'
[[message]]
key = 'entry_board_search_init'
old = '指定を初期化'
new = 'Reset Search'
[[message]]
key = 'entry_board_search_word1'
old = '～'
new = '～'
[[message]]
key = 'entry_board_search_exec_search'
old = '検索する'
new = 'Search'
[[message]]
key = 'entry_board_search_cancel'
old = 'キャンセルする'
new = 'Cancel'
[[message]]
key = 'entry_board_search_serach_level'
old = 'レベルを指定して探す'
new = 'Search by Level'
[[message]]
key = 'entry_board_pop_reqruit_all'
old = '全て'
new = 'All'
[[message]]
key = 'entry_board_pop_reqruit_reqruit'
old = '募集する'
new = 'Recruit'
[[message]]
key = 'entry_board_pop_reqruit_cancel'
old = 'キャンセル'
new = 'Cancel'
[[message]]
key = 'entry_board_reqruit_entry'
old = 'エントリーを指定してください'
new = 'Please setup your entry'
[[message]]
key = 'entry_board_reqruit_comment'
old = 'Comment'
new = 'Comment'
[[message]]
key = 'entry_board_reqruit_level'
old = 'レベル制限'
new = 'Level Restriction'
[[message]]
key = 'entry_board_reqruit_job'
old = 'ジョブ制限'
new = 'Job Restriction'
[[message]]
key = 'entry_board_reqruit_password'
old = 'パスワード設定'
new = 'Set Password'
[[message]]
key = 'entry_board_reqruit_word1'
old = '<VAL>.'
new = '<VAL>.'
[[message]]
key = 'entry_board_reqruit_osusume'
old = 'オススメ'
new = 'Recommended'
[[message]]
key = 'entry_board_reqruit_reqruit'
old = '募集する'
new = 'Recruit'
[[message]]
key = 'entry_board_reqruit_cancel'
old = 'キャンセル'
new = 'Cancel'
[[message]]
key = 'entry_board_reqruit_word2'
old = '～'
new = '～'
[[message]]
key = 'entry_board_info_memberlist'
old = 'Member List'
new = 'Member List'
[[message]]
key = 'entry_board_info_option'
old = 'Option'
new = 'Option'
[[message]]
key = 'entry_board_info_password_on'
old = 'パスワード：'
new = 'Password:'
[[message]]
key = 'entry_board_info_job_on'
old = 'ジョブ指定：'
new = 'Set Jobs:'
[[message]]
key = 'entry_board_info_word1'
old = '<VAL>/<VAL>'
new = '<VAL>/<VAL>'
[[message]]
key = 'entry_board_pop_event_top_entry'
old = '参加中'
new = 'Participating'
[[message]]
key = 'entry_board_mission_info_reward'
old = '報酬'
new = 'Reward'
[[message]]
key = 'entry_board_mission_info_entry_num'
old = '<VAL>人専用コンテンツ'
[[message]]
key = 'entry_board_mission_info_recommand'
old = '推奨'
new = 'Recommended'
[[message]]
key = 'entry_board_mission_info_war_situation'
old = '戦況'
[[message]]
key = 'entry_board_mission_info_decide'
old = '決定'
new = 'OK'
[[message]]
key = 'entry_board_mission_info_cancel'
old = 'キャンセル'
new = 'Cancel'
[[message]]
key = 'entry_board_search_designate_lv'
old = 'レベルを指定する'
new = 'Specify Level'
[[message]]
key = 'entry_board_or_more'
old = '以上'
new = 'or more'
[[message]]
key = 'entry_board_or_less'
old = '以下'
new = 'or less'
[[message]]
key = 'entry_board_info_no'
old = '戻る'
[[message]]
key = 'entry_board_info_member_check'
old = 'メンバー確認'
new = 'Check Members'
[[message]]
key = 'entry_board_info_limit_lv'
old = 'レベル制限：'
new = 'Level Limit:'
[[message]]
key = 'entry_board_contents_title_e'
old = 'Contents'
new = 'Contents'
[[message]]
key = 'entry_board_contents_title_j'
old = 'コンテンツ窓口'
new = 'Contents'
[[message]]
key = 'entry_board_contents_event'
old = 'レスタニアニュースで確認'
new = 'View Lestania News'
[[message]]
key = 'entry_board_mission_info_condition'
old = '受注条件'
new = 'Accept Requirements'
[[message]]
key = 'entry_board_info_no_designate_job'
old = 'ジョブ指定なし'
new = 'Any Job'
[[message]]
key = 'entry_borad_contents_num'
old = '<VAL>'
new = '<VAL>'
[[message]]
key = 'entry_board_info_memberlist_j'
old = 'メンバーリスト'
new = 'Member List'
[[message]]
key = 'entry_board_enter_password'
old = 'パスワードを入力してください'
new = 'Please enter your password.'
[[message]]
key = 'entry_board_btn_searth_another'
old = '別エントリー検索'
new = 'Search Again'
[[message]]
key = 'entry_board_set'
old = 'あり'
new = 'Yes'
[[message]]
key = 'entry_board_unset'
old = 'なし'
new = 'None'
[[message]]
key = 'entry_board_level_band'
old = 'min<VAL>～max<VAL>'
new = '<VAL>～<VAL>'
[[message]]
key = 'entry_board_unsatisfied'
old = '募集条件を満たしていません'
new = 'You do not meet the recruitment conditions'
[[message]]
key = 'entry_board_lv_limit1'
old = 'レベル制限：'
new = 'Level Limit: '
[[message]]
key = 'entry_board_lv_limit2'
old = 'レベル制限'
new = 'Level Limit'
[[message]]
key = 'entry_board_job_limit1'
old = 'ジョブ指定'
new = 'Job Specified'
[[message]]
key = 'entry_board_job_limit2'
old = 'ジョブ指定：'
new = 'Job Specified:'
[[message]]
key = 'entry_board_pass_limit1'
old = 'パスワード：'
new = 'Password:'
[[message]]
key = 'entry_board_pass_limit2'
old = 'パスワード設定'
new = 'Password Setting'
[[message]]
key = 'entry_board_time_gather'
old = '募集時間：'
new = 'Time:'
[[message]]
key = 'entry_board_num_menber'
old = '募集人数：'
new = 'Members:'
[[message]]
key = 'entry_board_is_cancel_make'
old = '募集をとりやめますか？'
new = 'Do you want to cancel recruitment?'
[[message]]
key = 'entry_board_buttonguid_membercheck'
old = 'パーティーメンバー確認'
new = 'Confirm Party Members'
[[message]]
key = 'entry_board_fail_search'
old = '検索結果は0件でした'
new = 'There was 0 search results.'
[[message]]
key = 'entry_board_search_search_party'
old = 'パーティーメンバー'
new = 'Party Members'
[[message]]
key = 'entry_board_search_search_groupchat'
old = 'グループチャット'
new = 'Group Chat'
[[message]]
key = 'entry_board_info_comment'
old = 'コメント　：'
new = 'Comment:'
[[message]]
key = 'entry_board_pop_event_info_ranking'
old = 'ランキング順位'
new = 'Ranking'
[[message]]
key = 'entry_board_pop_event_info_score_technical'
old = 'テクニカルスコア'
new = 'Technical Score'
[[message]]
key = 'entry_board_pop_event_info_score_total'
old = 'トータルスコア'
new = 'Total Score'
[[message]]
key = 'entry_board_pop_event_info_ranking_unit'
old = '位'
new = 'Rank'
[[message]]
key = 'entry_board_num_sortie_possible'
old = '出撃可能人数：'
new = 'Sortie Minimum:'
[[message]]
key = 'entry_board_mission_info_required'
old = '必須'
new = 'Req'
[[message]]
key = 'entry_board_mission_info_ir_condition'
old = 'アイテムランクが<VAL>以上 （現在のIR.<VAL>）'
new = 'Item Rank <VAL> or more (Current IR. <VAL>)'
[[message]]
key = 'entry_board_reqruit_ir'
old = 'IR制限'
new = 'IR Limit'
[[message]]
key = 'entry_board_reqruit_ir_normal'
old = '装備品の平均'
new = 'Equipment Average'
[[message]]
key = 'entry_board_reqruit_ir_mainwp'
old = 'メイン武器のみ'
new = 'Main Weapon Only'
[[message]]
key = 'entry_board_reqruit_ir_jobrole'
old = 'IR制限の対象ジョブロール'
new = 'Target Job Roles for IR Limit'
[[message]]
key = 'entry_board_reqruit_ir_jobrole_attacker'
old = 'アタッカー'
new = 'Attacker'
[[message]]
key = 'entry_board_reqruit_ir_jobrole_healer'
old = 'ヒーラー'
new = 'Healer'
[[message]]
key = 'entry_board_reqruit_ir_jobrole_tank'
old = 'タンク'
new = 'Tank'
[[message]]
key = 'entry_board_info_ir_limit'
old = 'IR制限：'
new = 'IR Lmt:'
[[message]]
key = 'entry_board_info_ir_num'
old = 'IR数値：'
new = 'IR Num: '
[[message]]
key = 'entry_board_info_ir_jobrole'
old = 'IR対象：'
new = 'IR Tgt:'
[[message]]
key = 'entry_board_set_ir_normal'
old = 'あり(装備品の平均)'
new = 'Yes (Equip Avg)'
[[message]]
key = 'entry_board_set_ir_mainwp'
old = 'あり(メイン武器のみ)'
new = 'Yes (Main Weap Only)'
[[message]]
key = 'entry_board_ir_band'
old = 'min<VAL>～'
new = 'min<VAL>～'
[[message]]
key = 'entry_board_search_tab_acquaintance'
old = '知り合い検索'
new = 'Acquaintance Search'
[[message]]
key = 'entry_board_search_tab_status'
old = '詳細検索'
new = 'Advanced Search'
[[message]]
key = 'entry_board_search_serach_ir'
old = 'IRを指定して探す'
new = 'Search by IR'
[[message]]
key = 'entry_board_search_designate_ir'
old = 'IRを指定する'
new = 'Specify IR'
[[message]]
key = 'entry_board_mission_info_bt_multi'
old = 'マルチプレイ'
new = 'Multi Play'
[[message]]
key = 'entry_board_mission_info_bt_solo'
old = 'ソロプレイ'
new = 'Solo Play'
[[message]]
key = 'entry_board_mission_info_attention'
old = '注意事項'
[[message]]
key = 'entry_board_mission_info_attention_clan'
old = '''
マルチプレイでのエントリーボード検索はできません
エントリーボード招待やパーティー招待などの機能を
使用して、他のプレイヤーを募集することが可能です'''
[[message]]
key = 'entry_board_mission_pb_type01_info'
old = 'インフォメーション'
[[message]]
key = 'entry_board_mission_pb_type01_info_txt'
old = '''
パーティー募集掲示板で集合したパーティーは
特定コンテンツ用パーティーではなく
通常のパーティーとなります
特定コンテンツに参加するには、
対象のコンテンツNPCのエントリーボードを
使用してください'''
[[message]]
key = 'entry_board_pop_event_info_dp_pos'
old = '<UNTN DP>'
[[message]]
key = 'entry_board_pop_event_info_dp_acc'
old = 'ウォーミッション累積ポイント'
new = 'War Mission Accumulated Points'
[[message]]
key = 'entry_board_wm_rank_info'
old = 'ランク詳細（指定<UNIT DP>以上）'
new = 'Rank Details (Specified <UNIT DP> or more)'
[[message]]
key = 'entry_board_wm_rank_s'
old = 'Ｓランク ： <VAL DP>'
new = 'S Rank: <VAL DP>'
[[message]]
key = 'entry_board_wm_rank_a'
old = 'Ａランク ： <VAL DP>'
new = 'A Rank: <VAL DP>'
[[message]]
key = 'entry_board_wm_rank_b'
old = 'Ｂランク ： <VAL DP>'
new = 'B Rank: <VAL DP>'
[[message]]
key = 'entry_board_wm_rank_c'
old = 'Ｃランク ： <VAL DP>'
new = 'C Rank: <VAL DP>'
[[message]]
key = 'entry_board_wm_rank_d'
old = 'Ｄランク ： <VAL DP>'
new = 'D Rank: <VAL DP>'
[[message]]
key = 'entry_board_recommend_counter_skill_title'
old = '推奨ドラゴンアビリティ'
new = 'Recommended Dragon Ability'
[[message]]
key = 'entry_board_playable_time_header'
old = '出撃可能時間'
new = 'Sortie Time'
[[message]]
key = 'entry_board_playable_time_info'
old = '<DATE> - <DATE>'
new = '<DATE> - <DATE>'
[[message]]
key = 'entry_board_dra_skill_msg_001'
old = 'ドラゴンアビリティ指定'
new = 'Dragon Ability Designation'
[[message]]
key = 'entry_board_dra_skill_msg_002'
old = 'ドラゴンアビリティ情報'
new = 'Dragon Ability Information'
[[message]]
key = 'entry_board_dra_skill_msg_003'
old = 'ボーナスドラゴンアビリティ'
new = 'Bonus Dragon Ability'
[[message]]
key = 'entry_board_dra_skill_msg_004'
old = 'パーティー合計='
new = 'Party total = '
[[message]]
key = 'entry_board_dra_skill_msg_005'
old = '個人合計='
new = 'Personal total = '
[[message]]
key = 'entry_board_dra_skill_msg_006'
old = '発動中'
new = 'Active'
[[message]]
key = 'entry_board_dra_skill_msg_007'
old = '―'
new = '-'
[[message]]
key = 'entry_board_dra_skill_msg_008'
old = '未発動'
new = 'Inactive'
[[message]]
key = 'entry_board_dra_skill_msg_009'
old = '有利：'
new = 'Advantagous: '
[[message]]
key = 'entry_board_dra_skill_msg_010'
old = '適正：'
new = 'Reasonable: '
[[message]]
key = 'entry_board_dra_skill_msg_011'
old = '不利：'
new = 'Disadvantagous: '
[[message]]
key = 'entry_board_dra_skill_msg_012'
old = '募集：'
new = 'Recruit: '
[[message]]
key = 'entry_board_dra_skill_msg_013'
old = 'ボーナス発動'
new = 'Bonus activation'
