[[message]]
key = 'hud_job_hunter_normal_arrow'
old = '通常矢'
new = 'Normal Arrow'
[[message]]
key = 'hud_disp_level'
old = 'LV.'
new = 'LV.'
[[message]]
key = 'hud_quest_qo'
old = 'Quest Owner'
new = 'Quest Owner'
[[message]]
key = 'hud_quest_gm'
old = 'Grand Mission'
new = 'Grand Mission'
[[message]]
key = 'hud_job_hunter_change_arrow'
old = '矢切替'
new = 'Change Arrow'
[[message]]
key = 'hud_job_sealedsage_change_attribution'
old = '属性切替'
new = 'Change Attribute'
[[message]]
key = 'hud_job_unequipped'
old = 'None'
new = 'None'
[[message]]
key = 'hud_status_standby'
old = 'スタンバイOK'
new = 'Standby OK'
[[message]]
key = 'hud_status_away'
old = '離席中'
new = 'Away'
[[message]]
key = 'hud_status_event'
old = 'イベント'
new = 'Event'
[[message]]
key = 'hud_quest_qg_time'
old = 'Time'
new = 'Time'
[[message]]
key = 'hud_quest_qg_point'
old = 'Score'
new = 'Score'
[[message]]
key = 'hud_quest_qg_pt'
old = 'pt'
new = 'pt'
[[message]]
key = 'hud_quest_qg_sec'
old = 'sec'
new = 'sec'
[[message]]
key = 'hud_status_ailment_sec'
old = '秒'
new = 'sec'
[[message]]
key = 'hud_status_ailment_stamina'
old = 'スタミナ回復'
new = 'Stamina Recovery'
[[message]]
key = 'hud_get_announce_bo'
old = '<VAL> <UNIT BO>'
new = '<VAL> <UNIT BO>'
[[message]]
key = 'hud_get_announce_g'
old = '<VAL> <UNIT G>'
new = '<VAL> <UNIT G>'
[[message]]
key = 'hud_get_announce_r'
old = '<VAL> <UNIT R>'
new = '<VAL> <UNIT R>'
[[message]]
key = 'hud_get_announce_xp'
old = '<VAL> <UNIT XP>'
new = '<VAL> <UNIT XP>'
[[message]]
key = 'hud_quest_ann_caution_deco'
old = 'Defeat the enemy !'
new = 'Defeat the enemy!'
[[message]]
key = 'hud_pawn_ann_lost'
old = '<VAL> がポーン郷にある異界の狭間へ送られました'
new = '<VAL> was sent to the Rift within Pawn Cathedral'
[[message]]
key = 'hud_pawn_ann_rescue_start'
old = '<VAL> を襲いかかる敵から救出せよ'
new = 'Rescue <VAL> from the attacking enemies'
[[message]]
key = 'hud_pawn_ann_rescue_failed'
old = '<VAL> の呪縛を解くことができなかった'
[[message]]
key = 'hud_pawn_ann_rescue_clear'
old = '<VAL> の呪縛が解け、リムの淵辺で目を覚ました'
[[message]]
key = 'hud_pawn_ann_resurrection'
old = '<VAL> が復活し、待機状態に戻りました'
new = '<VAL> rescued and returned to standby'
[[message]]
key = 'hud_disp_infinity'
old = '∞'
new = '∞'
[[message]]
key = 'hud_get_announce_pawnlvup'
old = '<NAME PAWN>が<LEVEL>にUPしました'
[[message]]
key = 'hud_enemy_nodamage'
old = 'Invulnerable'
new = 'Invulnerable'
[[message]]
key = 'hud_enemy_engage'
old = 'In Battle !'
new = 'In Combat!'
[[message]]
key = 'hud_gauge_sorcery_bonus'
old = '× <VAL>'
new = '× <VAL>'
[[message]]
key = 'hud_gauge_sorcery_button'
old = '<KC CHANGE_MODE>'
new = '<KC CHANGE_MODE>'
[[message]]
key = 'hud_quest_em'
old = 'Extreme Mission'
new = 'Extreme Mission'
[[message]]
key = 'hud_status_disconnect'
old = '回線切断中'
new = 'Disconnected'
[[message]]
key = 'hud_job_alchemist_normal_medal'
old = '遅延のエリクシル'
new = 'Torpor Elixir'
[[message]]
key = 'hud_job_alchemist_change_medal'
old = 'エリクシル切替'
new = 'Change Elixir'
[[message]]
key = 'hud_skill_move'
old = '発動'
new = 'Activate'
[[message]]
key = 'hud_charges_others'
old = ' その他×<VAL>'
new = 'Other×<VAL>'
[[message]]
key = 'hud_recommend_level'
old = 'LV.%d'
new = 'LV.%d'
[[message]]
key = 'hud_get_announce_bo_ex'
old = '<VAL> <VAL> <UNIT BO>'
new = '<VAL> <VAL> <UNIT BO>'
[[message]]
key = 'hud_get_announce_r_ex'
old = '<VAL> <VAL> <UNIT R>'
new = '<VAL> <VAL> <UNIT R>'
[[message]]
key = 'hud_get_announce_xp_ex'
old = '<VAL> <VAL> <UNIT XP>'
new = '<VAL> <VAL> <UNIT XP>'
[[message]]
key = 'hud_generalpurpose_clear_deco'
old = 'Defeated the enemy !'
new = 'Defeated the enemy!'
[[message]]
key = 'hud_change_tx_tank'
old = '<PADM><ICON PAD_L></PADM><KEYM><ICON MOUSE></KEYM>'
new = '<PADM><ICON PAD_L></PADM><KEYM><ICON MOUSE></KEYM>'
[[message]]
key = 'hud_gauge_xp_next'
old = 'Next '
new = 'Next '
[[message]]
key = 'hud_get_announce_g_ex'
old = '<VAL> <VAL> <UNIT G>'
new = '<VAL> <VAL> <UNIT G>'
[[message]]
key = 'hud_get_announce_goldstone'
old = '<VAL> @'
new = '<VAL> @'
[[message]]
key = 'hud_get_announce_silvertickets'
old = '<VAL> _|'
new = '<VAL> _|'
[[message]]
key = 'hud_map_guide_lock'
old = 'ロック'
new = 'Lock'
[[message]]
key = 'hud_map_guide_scaling'
old = '拡縮'
new = 'Scale'
[[message]]
key = 'hud_map_guide_freemarker'
old = 'フリーマーカー'
new = 'Waypoint'
[[message]]
key = 'hud_map_guide_cursor'
old = 'カーソル移動'
new = 'Move Cursor'
[[message]]
key = 'hud_map_guide_operation'
old = 'ミニマップ操作'
new = 'Expand'
[[message]]
key = 'hud_map_guide_zoom'
old = 'ズームイン/アウト'
new = 'Zoom In/Out'
[[message]]
key = 'hud_get_announce_rp'
old = '<VAL> <UNIT RP>'
new = '<VAL> <UNIT RP>'
[[message]]
key = 'hud_get_announce_rp_ex'
old = '<VAL> <VAL> <UNIT RP>'
new = '<VAL> <VAL> <UNIT RP>'
[[message]]
key = 'hud_commongauge_button_barrage_square'
old = '<KC ATTACK1>'
new = '<KC ATTACK1>'
[[message]]
key = 'hud_commontext_sorcery_cs13'
old = '氷柱を放つ：'
new = 'Shoot Icicle:'
[[message]]
key = 'hud_commontext_sorcery_cs14'
old = 'アンカーを消滅させる：<KC TOUCH>'
[[message]]
key = 'hud_commongauge_button_barrage_triangle'
old = '<KC ATTACK2>'
new = '<KC ATTACK2>'
[[message]]
key = 'hud_commontext_all_reliefcancel'
old = '救済を中断する：<KC JUMP>'
new = 'Interrupt Help: <KC JUMP>'
[[message]]
key = 'hud_commontext_cs_button_square'
old = '<KC ATTACK1>'
new = '<KC ATTACK1>'
[[message]]
key = 'hud_commontext_cs_button_triangle'
old = '<KC ATTACK2>'
new = '<KC ATTACK2>'
[[message]]
key = 'hud_job_spiritlancer_change_item'
old = 'アイテム切替(仮)'
[[message]]
key = 'hud_job_spiritlancer_normal_item'
old = '【仮0】 HP回復'
[[message]]
key = 'hud_get_announce_pp'
old = '<VAL> <UNIT PP>'
new = '<VAL> <UNIT PP>'
[[message]]
key = 'hud_get_announce_pp_ex'
old = '<VAL> <VAL> <UNIT PP>'
new = '<VAL> <VAL> <UNIT PP>'
[[message]]
key = 'hud_caution_announce_warning_deco'
old = 'Defeat the dungeon enemy !'
new = 'Defeat the dungeon enemy!'
[[message]]
key = 'hud_caution_announce_clear_warning_deco'
old = 'Defeated the dungeon enemy !'
new = 'Defeated the dungeon enemy!'
[[message]]
key = 'hud_commontext_spiritlancer_nospirit'
old = 'No Spirits !'
new = 'No Spirits!'
[[message]]
key = 'hud_commontext_spiritlancer_cs08'
old = '支援を解除する：<KC JUMP>'
[[message]]
key = 'hud_map_guide_auto_scaling_lock'
old = '拡大固定'
new = 'Lock Expand'
[[message]]
key = 'hud_map_guide_auto_scaling_unlock'
old = '拡大固定解除'
new = 'Unlock Expand'
[[message]]
key = 'hud_announce_clan_dungeon_unlock'
old = '新たなクランダンジョンが解放されました'
new = 'A new Clan Dungeon has been unlocked'
[[message]]
key = 'hud_announce_first_discovered'
old = 'おめでとうございます！ この新種の第一発見者になりました！'
[[message]]
key = 'hud_announce_new_species_discovered'
old = 'お見事！ 新種のマンドラゴラを発見しました！'
[[message]]
key = 'hud_get_announce_dp'
old = '<VAL> <UNIT DP>'
[[message]]
key = 'hud_get_announce_dp_ex'
old = '<VAL> <VAL> <UNIT DP>'
[[message]]
key = 'hud_get_announce_hb'
old = '<VAL> <UNIT HB>'
[[message]]
key = 'hud_get_announce_hb_ex'
old = '<VAL> <VAL> <UNIT HB>'
[[message]]
key = 'hud_ordeal_ann_start'
old = '特殊条件を満たし、英霊の試練を攻略せよ'
[[message]]
key = 'hud_ordeal_ann_clear'
old = '特殊条件を満たし、英霊の試練を突破した'
[[message]]
key = 'hud_ordeal_ann_failed'
old = '特殊条件を満たせず、英霊の試練に失敗した'
[[message]]
key = 'hud_get_announce_ms'
old = '<VAL> =*'
[[message]]
key = 'hud_commontext_alchemist_cs12'
old = '支援を解除する：<KC JUMP>'
[[message]]
key = 'hud_get_announce_gdm'
old = '<VAL> $#'
[[message]]
key = 'hud_get_announce_sdm'
old = '<VAL> {#'
[[message]]
key = 'hud_get_announce_rdm'
old = '<VAL> }#'
[[message]]
key = 'hud_announce_bbi_clear'
old = '《%s》攻略！'
new = '"%s" cleared!'
[[message]]
key = 'hud_announce_bbi_comp'
old = '%sを踏破した！'
new = '%s traversed!'
[[message]]
key = 'hud_notice_no_charm_gauge'
old = '魔力が%sゲージ以上ありません'
new = 'Need %s magick gauge!'
[[message]]
key = 'hud_notice_no_charm_stack'
old = '魔力が%sスタック以上ありません'
new = 'Need %s magick stack!'
[[message]]
key = 'hud_name_om_safetydome'
old = '護身の結界'
new = 'Barrier of Defense'
[[message]]
key = 'hud_get_announce_gdm_ex'
old = '<VAL> <VAL> $#'
[[message]]
key = 'hud_get_announce_sdm_ex'
old = '<VAL> <VAL> {#'
[[message]]
key = 'hud_get_announce_rdm_ex'
old = '<VAL> <VAL> }#'
[[message]]
key = 'hud_quest_qg_chain'
old = 'Chain'
[[message]]
key = 'hud_dragon_skill_pl_1'
old = '“%s”を発動した！'
new = '"%s" has activated!'
[[message]]
key = 'hud_dragon_skill_pl_2'
old = '渾身の“%s”を発動した！'
new = '"%s" has fully activated!'
[[message]]
key = 'hud_dragon_skill_pl_0'
old = '“%s”を発動できなかった――'
new = '"%s" could not be activated'
[[message]]
key = 'hud_dark_dungeon_p_0'
old = 'ダンジョン内の異変を調査せよ'
new = 'Investigate the abnomalities in the dungeon'
[[message]]
key = 'hud_job_elementarcher_single'
old = 'シングルロックオン'
new = 'Single Lock On'
[[message]]
key = 'hud_job_elementarcher_multi'
old = 'マルチロックオン'
new = 'Multi Lock On'
[[message]]
key = 'hud_announce_dragon_skill_set'
old = 'ドラゴンアビリティが発動した！'
new = 'Dragon ability has activated!'