[[message]]
key = 'menu_cmn_skill_grand'
old = '地上'
new = 'Ground'
[[message]]
key = 'menu_cmn_skill_air'
old = '空中'
new = 'Air'
[[message]]
key = 'menu_cmn_skill_climb'
old = 'しがみつき'
new = 'Climb'
[[message]]
key = 'menu_cmn_weight_verylight'
old = 'Very Light'
new = 'Very Light'
[[message]]
key = 'menu_cmn_weight_light'
old = 'Light'
new = 'Light'
[[message]]
key = 'menu_cmn_weight_medium'
old = 'Medium'
new = 'Medium'
[[message]]
key = 'menu_cmn_weight_heavy'
old = 'Heavy'
new = 'Heavy'
[[message]]
key = 'menu_cmn_weight_beryheavy'
old = 'Very Heavy'
new = 'Very Heavy'
[[message]]
key = 'menu_cmn_weight_over'
old = 'Over'
new = 'Over'
[[message]]
key = 'menu_cmn_next'
old = 'Next'
new = 'Next'
[[message]]
key = 'menu_cmn_cost'
old = 'Cost'
new = 'Cost'
[[message]]
key = 'menu_cmn_hp'
old = 'HP'
new = 'HP'
[[message]]
key = 'menu_cmn_stamina'
old = 'ST'
new = 'ST'
[[message]]
key = 'menu_cmn_max'
old = 'MAX'
new = 'MAX'
[[message]]
key = 'menu_cmn_si_height'
old = '<VAL> cm'
new = '<VAL> cm'
[[message]]
key = 'menu_cmn_job'
old = 'Job'
new = 'Job'
[[message]]
key = 'menu_cmn_category'
old = 'Category'
new = 'Category'
[[message]]
key = 'menu_cmn_slash_val'
old = '/<VAL>'
new = '/<VAL>'
[[message]]
key = 'menu_cmn_val_slash_val'
old = '<VAL>/<VAL>'
new = '<VAL>/<VAL>'
[[message]]
key = 'menu_cmn_slash'
old = '/'
new = '/'
[[message]]
key = 'menu_cmn_filter'
old = 'フィルタ'
new = 'Filter'
[[message]]
key = 'menu_cmn_filter_off'
old = 'フィルタを解除'
new = 'Unfiltered'
[[message]]
key = 'menu_cmn_filter_select'
old = '適用するフィルタを選んでください'
new = 'Please select the filter to apply'
[[message]]
key = 'menu_cmn_header_item'
old = 'Item'
[[message]]
key = 'menu_cmn_header_storage'
old = 'Storage'
[[message]]
key = 'menu_cmn_open_online_shop'
old = 'オンラインショップを開く'
new = 'Open online shop'
[[message]]
key = 'menu_cmn_shortage_gs'
old = '''
<UNTN GS>が不足しています
（所持数：<HAVE GS>）'''
[[message]]
key = 'menu_cmn_item'
old = 'アイテム'
new = 'Item'
[[message]]
key = 'menu_cmn_receive_bag'
old = 'アイテムバッグに受け取る'
new = 'Receive in item bag'
[[message]]
key = 'menu_cmn_receive_box'
old = '保管ボックスに受け取る'
new = 'Receive in storage'
