[[message]]
key = 'FUNC_CLASS_NAME_3'
old = 'よろず屋'
new = 'General Shop'
[[message]]
key = 'FUNC_CLASS_NAME_4'
old = '道具屋'
new = 'Item Shop'
[[message]]
key = 'FUNC_CLASS_NAME_5'
old = '武具屋'
new = 'Equipment Shop'
[[message]]
key = 'FUNC_CLASS_NAME_6'
old = '素材屋'
new = 'Material Shop'
[[message]]
key = 'FUNC_CLASS_NAME_7'
old = '宿屋'
new = 'Inn'
[[message]]
key = 'FUNC_CLASS_NAME_8'
old = '武器屋'
new = 'Weapon Shop'
[[message]]
key = 'FUNC_CLASS_NAME_9'
old = '防具屋'
new = 'Armor Shop'
[[message]]
key = 'FUNC_CLASS_NAME_10'
old = '戦技補佐'
new = 'Arts Support'
[[message]]
key = 'FUNC_CLASS_NAME_11'
old = '転職・戦技補佐'
new = 'Vocation / Arts Support'
[[message]]
key = 'FUNC_CLASS_NAME_12'
old = 'グランドミッション'
new = 'Grand Mission'
[[message]]
key = 'FUNC_CLASS_NAME_13'
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
key = 'FUNC_CLASS_NAME_14'
old = 'クラン酒場'
new = 'Clan Tavern'
[[message]]
key = 'FUNC_CLASS_NAME_15'
old = 'クラフト係官'
new = 'Craft Officer'
[[message]]
key = 'FUNC_CLASS_NAME_16'
old = '美容院'
new = 'Beauty Salon'
[[message]]
key = 'FUNC_CLASS_NAME_17'
old = 'レスタニアニュース'
new = 'Lestania News'
[[message]]
key = 'FUNC_CLASS_NAME_18'
old = '竜力の継承'
new = 'Dragon Force Augmentation'
[[message]]
key = 'FUNC_CLASS_NAME_19'
old = 'オーブ交換：クレスト'
new = 'Orb Exchange: Crests'
[[message]]
key = 'FUNC_CLASS_NAME_20'
old = 'オーブ交換：珍品／素材'
new = 'Orb Exchange: Rare Items / Materials'
[[message]]
key = 'FUNC_CLASS_NAME_21'
old = 'エリアマスター'
new = 'Area Master'
[[message]]
key = 'FUNC_CLASS_NAME_22'
old = 'ジョブマスター'
new = 'Job Master'
[[message]]
key = 'FUNC_CLASS_NAME_24'
old = 'バザー'
new = 'Bazaar'
[[message]]
key = 'FUNC_CLASS_NAME_25'
old = '保管ボックス'
new = 'Storage Box'
[[message]]
key = 'FUNC_CLASS_NAME_26'
old = '納品ボックス'
new = 'Delivery Box'
[[message]]
key = 'FUNC_CLASS_NAME_27'
old = 'リムストーン'
new = 'Riftstone'
[[message]]
key = 'FUNC_CLASS_NAME_28'
old = '竜の礎'
new = "Dragon's Keystone"
[[message]]
key = 'FUNC_CLASS_NAME_29'
old = '拠点の礎'
new = 'Portcrystal'
[[message]]
key = 'FUNC_CLASS_NAME_30'
old = '竜の礎'
new = "Dragon's Keystone"
[[message]]
key = 'FUNC_CLASS_NAME_31'
old = 'クエストボード'
new = 'Quest Board'
[[message]]
key = 'FUNC_CLASS_NAME_32'
old = 'クランクエストボード'
new = 'Clan Quest Board'
[[message]]
key = 'FUNC_CLASS_NAME_33'
old = 'ランキングボード'
new = 'Ranking Board'
[[message]]
key = 'FUNC_CLASS_NAME_34'
old = '亡都の礎'
[[message]]
key = 'FUNC_CLASS_NAME_35'
old = '移送の楔'
[[message]]
key = 'FUNC_CLASS_NAME_36'
old = '記録官'
new = 'Historian'
[[message]]
key = 'FUNC_CLASS_NAME_37'
old = 'ポーンの復活'
new = 'Revive Pawn'
[[message]]
key = 'FUNC_CLASS_NAME_39'
old = 'エクストリームミッション'
new = 'Extreme Missions'
[[message]]
key = 'FUNC_CLASS_NAME_40'
old = '復活力の回復'
new = 'Recover Revival Power'
[[message]]
key = 'FUNC_CLASS_NAME_41'
old = '拠点用保管ボックス'
new = 'Camp Storage Box'
[[message]]
key = 'FUNC_CLASS_NAME_42'
old = 'ログインスタンプ'
new = 'Login Stamp'
[[message]]
key = 'FUNC_CLASS_NAME_43'
old = '報酬受け取り'
new = 'Receive Reward'
[[message]]
key = 'FUNC_CLASS_NAME_44'
old = 'トレジャーズロット'
new = 'Treasure Lot'
[[message]]
key = 'FUNC_CLASS_NAME_45'
old = '現れしポーン'
[[message]]
key = 'FUNC_CLASS_NAME_46'
old = '弱化の治療'
new = 'Treat Weakness'
[[message]]
key = 'FUNC_CLASS_NAME_47'
old = '戦徒の契り'
new = "Myrmidon's Pledge"
[[message]]
key = 'FUNC_CLASS_NAME_48'
old = '鑑定交換'
new = 'Appraisal Exchange'
[[message]]
key = 'FUNC_CLASS_NAME_49'
old = 'パートナーポーン'
new = 'Partner Pawn'
[[message]]
key = 'FUNC_CLASS_NAME_50'
old = '戦技の継承'
new = 'Skill Augmentation'
[[message]]
key = 'FUNC_CLASS_NAME_51'
old = 'アチーブメント'
new = 'Achievements'
[[message]]
key = 'FUNC_CLASS_NAME_52'
old = '格納チェスト'
new = 'Storage Chest'
[[message]]
key = 'FUNC_CLASS_NAME_53'
old = 'ジョブ解放'
new = 'Vocation Unlock'
[[message]]
key = 'FUNC_CLASS_NAME_54'
old = 'ボックストレジャーズロット'
new = 'Box Treasure Lot'
[[message]]
key = 'FUNC_CLASS_NAME_55'
old = 'ポーン遠征隊'
new = 'Pawn Expedition Corps'
[[message]]
key = 'FUNC_CLASS_NAME_56'
old = '遠征成果の確認'
new = 'Check Expedition Result'
[[message]]
key = 'FUNC_CLASS_NAME_57'
old = 'プレイポイントショップ'
new = 'Play Point Shop'
[[message]]
key = 'FUNC_CLASS_NAME_58'
old = 'クラン拠点管理'
new = 'Clan Hall Management'
[[message]]
key = 'FUNC_CLASS_NAME_59'
old = '戦技練習'
new = 'Warfare Practice'
[[message]]
key = 'FUNC_CLASS_NAME_60'
old = 'クランダンジョン'
new = 'Clan Dungeon'
[[message]]
key = 'FUNC_CLASS_NAME_61'
old = ''
new = ''
[[message]]
key = 'FUNC_CLASS_NAME_62'
old = ''
new = ''
[[message]]
key = 'FUNC_CLASS_NAME_63'
old = ''
new = ''
[[message]]
key = 'FUNC_CLASS_NAME_64'
old = '絶技の継承'
new = 'Special Skill Augmentation'
[[message]]
key = 'FUNC_CLASS_NAME_65'
old = 'ジョブエンブレム'
new = 'Vocation Emblem'
[[message]]
key = 'FUNC_CLASS_NAME_66'
old = 'サブストーリーログ'
new = 'Substory Log'
[[message]]
key = 'FUNC_CLASS_NAME_67'
old = '英霊眠りし道'
new = 'Heroic Spirit Sleeping Path'
[[message]]
key = 'FUNC_CLASS_NAME_68'
old = '魂を捧げる'
new = 'Give Spirits'
[[message]]
key = 'FUNC_CLASS_NAME_69'
old = 'ウォーミッション'
new = 'War Missions'
[[message]]
key = 'FUNC_CLASS_NAME_70'
old = 'ドミニオンポイントショップ'
new = 'Dominion Point Shop'
[[message]]
key = 'FUNC_CLASS_NAME_71'
old = '転生'
new = 'Reincarnation'
[[message]]
key = 'FUNC_CLASS_NAME_72'
old = '武具のカスタムメイド'
new = 'Custom-made Arms'
[[message]]
key = 'FUNC_CLASS_NAME_73'
old = '武具の資源分解'
new = 'Arms Resource Disassembly'
[[message]]
key = 'FUNC_CLASS_NAME_74'
old = '冒パスショップ'
new = 'Adventure Pass Shop'
[[message]]
key = 'FUNC_CLASS_NAME_75'
old = ''
new = ''
[[message]]
key = 'FUNC_CLASS_NAME_76'
old = ''
new = ''
[[message]]
key = 'FUNC_CLASS_NAME_77'
old = ''
new = ''
[[message]]
key = 'FUNC_CLASS_NAME_78'
old = 'アチーブメント：王家再興'
new = 'Achievements: Royal Family Restoration'
[[message]]
key = 'FUNC_CLASS_NAME_80'
old = '紋章メダル交換'
new = 'Emblem Medal Exchange'
[[message]]
key = 'FUNC_CLASS_NAME_81'
old = 'おでかけ支援サービス'
new = 'Outing Support Service'
[[message]]
key = 'FUNC_CLASS_NAME_82'
old = '他人の自室訪問'
new = "Visit Another's Room"
[[message]]
key = 'FUNC_CLASS_NAME_83'
old = 'スペシャルクエストボード'
new = 'Special Quest Board'
[[message]]
key = 'FUNC_CLASS_NAME_84'
old = '大口納品報酬確認'
new = 'Large Delivery Reward Review'
[[message]]
key = 'FUNC_CLASS_NAME_85'
old = '自室訪問設定'
new = 'My Room Visit Setup'
[[message]]
key = 'FUNC_CLASS_NAME_86'
old = '冒険ガイド'
new = 'Adventure Guide'
[[message]]
key = 'FUNC_CLASS_NAME_87'
old = '募集掲示板'
new = 'Recruitment Board'
[[message]]
key = 'FUNC_CLASS_NAME_88'
old = '効果の封印'
new = 'Effect Seal'
[[message]]
key = 'FUNC_CLASS_NAME_89'
old = '黒呪アイテムの鑑定'
new = 'Bitterblack Item Appraisal'
[[message]]
key = 'FUNC_CLASS_NAME_90'
old = '具現化'
[[message]]
key = 'FUNC_CLASS_NAME_91'
old = '探索結果の報告'
new = 'Report Search Results'
[[message]]
key = 'FUNC_CLASS_NAME_93'
old = ''
new = ''
[[message]]
key = 'FUNC_CLASS_NAME_94'
old = ''
new = ''
[[message]]
key = 'FUNC_CLASS_NAME_95'
old = '印記章交換'
new = 'Medal Exchange'
[[message]]
key = 'FUNC_CLASS_NAME_96'
old = '大口納品イベント'
new = 'Large Delivery Event'
[[message]]
key = 'FUNC_CLASS_NAME_97'
old = '黒呪ショップ'
new = 'Bitterblack Shop'
[[message]]
key = 'FUNC_CLASS_NAME_98'
old = ''
new = ''
[[message]]
key = 'FUNC_CLASS_NAME_99'
old = 'ワイルドハント'
new = 'Wild Hunt'
[[message]]
key = 'FUNC_CLASS_NAME_100'
old = 'ハイオーブ交換'
new = 'High Orb Exchange'
[[message]]
key = 'FUNC_CLASS_NAME_101'
old = 'ドラゴンアビリティの合成'
new = 'Dragon Ability Synthesis'
[[message]]
key = 'FUNC_CLASS_NAME_102'
old = '竜防具の鑑定交換'
new = 'Dragon Armor Appraisal'
[[message]]
key = 'FUNC_CLASS_NAME_103'
old = 'リワードミッション'
new = 'Reward Mission'
[[message]]
key = 'FUNC_CLASS_NAME_104'
old = 'リワードメダル交換'
new = 'Reward Medal Exchange'
