[[message]]
key = 'CONDITION_NAME_10'
old = '毒'
new = 'Poison'
[[message]]
key = 'CONDITION_NAME_11'
old = '遅延'
new = 'Slow'
[[message]]
key = 'CONDITION_NAME_12'
old = '睡眠'
new = 'Sleep'
[[message]]
key = 'CONDITION_NAME_13'
old = '気絶'
new = 'Stun'
[[message]]
key = 'CONDITION_NAME_14'
old = '水濡れ'
new = 'Drenched'
[[message]]
key = 'CONDITION_NAME_15'
old = '油濡れ'
new = 'Tarred'
[[message]]
key = 'CONDITION_NAME_16'
old = 'スキル封印'
new = 'Skills Stifled'
[[message]]
key = 'CONDITION_NAME_17'
old = '呪い'
new = 'Cursed'
[[message]]
key = 'CONDITION_NAME_18'
old = '軟化'
new = 'Softened'
[[message]]
key = 'CONDITION_NAME_19'
old = '石化'
new = 'Petrification'
[[message]]
key = 'CONDITION_NAME_20'
old = '黄金化'
new = 'Golden'
[[message]]
key = 'CONDITION_NAME_21'
old = '延焼'
new = 'Caught Fire'
[[message]]
key = 'CONDITION_NAME_22'
old = '凍結'
new = 'Frozen Solid'
[[message]]
key = 'CONDITION_NAME_23'
old = '感電'
new = 'Shocked'
[[message]]
key = 'CONDITION_NAME_24'
old = '聖吸'
new = 'Holy Drain'
[[message]]
key = 'CONDITION_NAME_25'
old = '闇霧'
new = 'Blinded'
[[message]]
key = 'CONDITION_NAME_26'
old = '炎防低下'
new = 'Fire Resist Down'
[[message]]
key = 'CONDITION_NAME_27'
old = '氷防低下'
new = 'Ice Resist Down'
[[message]]
key = 'CONDITION_NAME_28'
old = '雷防低下'
new = 'Thunder Resist Down'
[[message]]
key = 'CONDITION_NAME_29'
old = '聖防低下'
new = 'Holy Resist Down'
[[message]]
key = 'CONDITION_NAME_30'
old = '闇防低下'
new = 'Dark Resist Down'
[[message]]
key = 'CONDITION_NAME_31'
old = '物攻低下'
new = 'Physical Attack Down'
[[message]]
key = 'CONDITION_NAME_32'
old = '物防低下'
new = 'Physical Defense Down'
[[message]]
key = 'CONDITION_NAME_33'
old = '魔攻低下'
new = 'Magick Attack Down'
[[message]]
key = 'CONDITION_NAME_34'
old = '魔防低下'
new = 'Magick Defense Down'
[[message]]
key = 'CONDITION_NAME_35'
old = '弱化'
new = 'Weakened'
[[message]]
key = 'CONDITION_NAME_36'
old = '物攻上昇'
new = 'Physical Attack Up'
[[message]]
key = 'CONDITION_NAME_37'
old = '物防上昇'
new = 'Physical Defense Up'
[[message]]
key = 'CONDITION_NAME_38'
old = '魔攻上昇'
new = 'Magick Attack Up'
[[message]]
key = 'CONDITION_NAME_39'
old = '魔防上昇'
new = 'Magick Defense Up'
[[message]]
key = 'CONDITION_NAME_40'
old = '吹き飛ばし力上昇'
new = 'Blow Power Up'
[[message]]
key = 'CONDITION_NAME_41'
old = '耐久力上昇'
new = 'Endurance Up'
[[message]]
key = 'CONDITION_NAME_42'
old = '生命治癒力上昇'
new = 'Healing Power Up'
[[message]]
key = 'CONDITION_NAME_43'
old = '炎防上昇'
new = 'Fire Resist Up'
[[message]]
key = 'CONDITION_NAME_44'
old = '氷防上昇'
new = 'Ice Resist Up'
[[message]]
key = 'CONDITION_NAME_45'
old = '雷防上昇'
new = 'Thunder Resist Up'
[[message]]
key = 'CONDITION_NAME_46'
old = '聖防上昇'
new = 'Holy Resist Up'
[[message]]
key = 'CONDITION_NAME_47'
old = '闇防上昇'
new = 'Dark Resist Up'
[[message]]
key = 'CONDITION_NAME_48'
old = '炎攻付加'
new = 'Add Fire Attack'
[[message]]
key = 'CONDITION_NAME_49'
old = '氷攻付加'
new = 'Add Ice Attack'
[[message]]
key = 'CONDITION_NAME_50'
old = '雷攻付加'
new = 'Add Thunder Attack'
[[message]]
key = 'CONDITION_NAME_51'
old = '聖攻付加'
new = 'Add Holy Attack'
[[message]]
key = 'CONDITION_NAME_52'
old = '闇攻付加'
new = 'Add Dark Attack'
[[message]]
key = 'CONDITION_NAME_53'
old = '体力上昇'
new = 'Max Health Up'
[[message]]
key = 'CONDITION_NAME_54'
old = 'スタミナ上昇'
new = 'Max Stamina Up'
[[message]]
key = 'CONDITION_NAME_57'
old = '強化'
new = 'Strengthed'
[[message]]
key = 'CONDITION_NAME_58'
old = '侵食・軽度'
new = 'Slight Corruption'
[[message]]
key = 'CONDITION_NAME_59'
old = '侵食・重度'
new = 'Severe Corruption'
[[message]]
key = 'CONDITION_NAME_60'
old = '侵食・危険'
new = 'Critical Corruption'
[[message]]
key = 'CONDITION_NAME_61'
old = '侵食耐性'
new = 'Corruption Resist'
[[message]]
key = 'CONDITION_NAME_62'
old = 'アイテム封印'
new = 'Items Sealed'
[[message]]
key = 'CONDITION_NAME_63'
old = '敵視上昇'
new = 'Hostilty Increased'
[[message]]
key = 'CONDITION_NAME_64'
old = '異界落とし'
new = 'Spirited Away'
[[message]]
key = 'CONDITION_NAME_65'
old = '寄生毒'
new = 'Parasitic Poison'
[[message]]
key = 'CONDITION_NAME_66'
old = '寄生毒'
new = 'Parasitic Poison'
[[message]]
key = 'CONDITION_NAME_67'
old = '抗蟲状態'
new = 'Parasitic Poison Resist'
[[message]]
key = 'CONDITION_NAME_68'
old = '全攻撃能力上昇'
new = 'Extreme Attack Up'
[[message]]
key = 'CONDITION_NAME_69'
old = '全防御能力上昇'
new = 'Extreme Defense Up'
[[message]]
key = 'CONDITION_NAME_70'
old = '闇炎'
new = 'Dark Flame'
[[message]]
key = 'CONDITION_NAME_71'
old = '闇牢'
new = 'Dark Prison'
